table Saving_3sites
	isHidden
	lineageTag: 8691716a-5a9a-4c39-8134-3a3767ac0333

	column Site
		dataType: string
		isHidden
		lineageTag: 4a8530f1-21f8-4e04-8179-f0cc5b88d3f4
		summarizeBy: none
		sourceColumn: Site

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 07235ab3-a1ff-4d13-b3b1-3f4cec42c42a
		summarizeBy: count
		sourceColumn: ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Projected
		dataType: double
		isHidden
		lineageTag: 8c797c94-6100-4aef-b623-dddbe63e5e50
		summarizeBy: sum
		sourceColumn: Projected

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProjectName
		dataType: string
		isHidden
		lineageTag: 45f3749f-9b15-4a6d-8dee-c3082b5ddc6d
		summarizeBy: none
		sourceColumn: ProjectName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Saving_3sites = m
		mode: import
		source =
				let
				    Source = HistoryOverview,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"History_Overview.Brief Prepared by", "History_Overview.Category", "History_Overview.Digital Tech enabled", "History_Overview.ELT", "History_Overview.ELT details", "History_Overview.ELT L3", "History_Overview.ELT Level 2", "History_Overview.ELT Level 3", "History_Overview.ELT Level 4", "History_Overview.ELT_Details", "History_Overview.Finance Partner", "History_Overview.IL", "History_Overview.MPR line", "History_Overview.O Comments", "History_Overview.Operation Tracking", "History_Overview.Overall Status", "History_Overview.Platfrom", "History_Overview.Sponsor", "History_Overview.Sub category", "History_Overview.Summary of actions and mitigation plans", "History_Overview.Technology", "History_Overview.Week", "History_Overview.Year"}),
				    maxReport = List.Max(#"Removed Columns"[History_Overview.Report]),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each ([History_Overview.Report] = maxReport)),
				    #"Grouped Rows" = Table.Group(#"Filtered Rows", {"History_Overview.ELT Level 5", "History_Overview.ID_General"}, {{"Projected", each List.Sum([History_Overview.Value]), type nullable number}, {"ProjectName", each List.Max([#"History_Overview.Activity / Project Name"]), type nullable text}}),
				    #"Sorted Rows" = Table.Sort(#"Grouped Rows",{{"History_Overview.ELT Level 5", Order.Ascending}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Sorted Rows", each ([History_Overview.ELT Level 5] <> "Processing JIA")),
				    #"Extracted Text After Delimiter" = Table.TransformColumns(#"Filtered Rows1", {{"History_Overview.ELT Level 5", each Text.AfterDelimiter(_, " "), type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Extracted Text After Delimiter",{{"History_Overview.ID_General", "ID"}, {"History_Overview.ELT Level 5", "Site"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

