table 2025ProductivityTracker
	lineageTag: 31df5e6e-46e3-42ea-858c-95fc3530907e

	column Area
		dataType: string
		lineageTag: 82a88e4e-47a4-4fc1-b28f-2d490a9800ef
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column 'Dept.'
		dataType: string
		lineageTag: 508f5da7-e727-44b8-91fc-cdd583a50001
		summarizeBy: none
		sourceColumn: Dept.

		annotation SummarizationSetBy = Automatic

	column 'Project name'
		dataType: string
		lineageTag: fbb746fd-74cb-4ee3-bd80-24644cd8e28c
		summarizeBy: none
		sourceColumn: Project name

		annotation SummarizationSetBy = Automatic

	column 'Project leader'
		dataType: string
		lineageTag: 6b114df3-60f9-46f9-8689-a4ccafc086e6
		summarizeBy: none
		sourceColumn: Project leader

		annotation SummarizationSetBy = Automatic

	column 'Cost bucket'
		dataType: string
		lineageTag: c86b8a78-41c3-4b66-9422-9d048630575e
		summarizeBy: none
		sourceColumn: Cost bucket

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: b9a829b0-8ce9-4d25-a4e4-bcaa30972274
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Value Type'
		dataType: string
		lineageTag: aec58364-0717-4321-9522-4cf9a4f800f8
		summarizeBy: none
		sourceColumn: Value Type

		annotation SummarizationSetBy = Automatic

	column IL
		dataType: string
		lineageTag: d6664d70-8bb3-40a8-aec2-3149a73df2c1
		summarizeBy: none
		sourceColumn: IL

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: b5595308-e065-4d80-9007-6e76a9a5a0c9
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 6eb5e056-da73-4c21-94e1-7543618479e5
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 2025ProductivityTracker = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/Productivity2020/Shared%20Documents/General/Overall%20Productivity%20tracker/JIA%20Productivity%20tracker-Currently%20year.xlsx"), null, true),
				    #"Overall tracker_Sheet" = Source{[Item="Overall tracker",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Overall tracker_Sheet", [PromoteAllScalars=true]),
				    #"Removed Other Columns" = Table.SelectColumns(#"Promoted Headers",{"Area", "Dept.", "Project name", "Project leader", "Cost bucket", "Category", "Value Type", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "YTD Saving#(lf)(m DKK)", "Total Target#(lf)(m DKK)", "IL"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Other Columns",{"YTD Saving#(lf)(m DKK)", "Total Target#(lf)(m DKK)"}),
				    #"Filled Down" = Table.FillDown(#"Removed Columns",{"Project name", "Project leader", "Cost bucket", "Category", "IL"}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Filled Down", {"Area", "Dept.", "Project name", "Project leader", "Cost bucket", "Category", "Value Type", "IL"}, "Month", "Value"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Unpivoted Columns",{{"Value", type number}}),
				    #"Rounded Down" = Table.TransformColumns(#"Changed Type",{{"Value",each  Number.RoundDown(_,4)  }}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Rounded Down",{{"Month", Int64.Type}, {"Value", type number}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

