table OfficeStatus
	lineageTag: 48e11846-b77a-4594-a60d-ac77d428aef8

	measure ColorRepresent = ```
			
			    SWITCH(MAX('OfficeStatus'[Color]),
			        "#BFBFBF","Non Working Day",
			        "#7030A0","WFH",
			        "#FFFFFF","In Office",
			        "#FF0000","Sick Leave",
			        "#0070C0","Annual Leave",
			        "#000000","Business Trip",
			        "#FFFF00","Special Events",
			        "Training")
			        
			```
		lineageTag: 541ecb3c-a354-4fbc-bb70-aff0bed5012f

	column Month
		dataType: string
		isHidden
		lineageTag: 25eaf70c-f8c3-452c-a2d0-a212123383f4
		summarizeBy: none
		sourceColumn: Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WeekNo
		dataType: string
		lineageTag: 8ad085b4-d323-42d8-b588-3d0195bff246
		summarizeBy: none
		sourceColumn: WeekNo

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 8003a1a4-e2e0-4596-98af-108865f22705
		summarizeBy: none
		sourceColumn: Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Name
		dataType: string
		lineageTag: 1ab0ecc0-17fa-4af0-b0d6-1b0f2b13d63e
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: a87405c4-65ce-40d6-b252-7bd840fece10
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column 'Start of Week'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c5ed48c1-72b1-4308-b960-04f420b8aa3e
		summarizeBy: none
		sourceColumn: Start of Week

		variation Variation
			isDefault
			relationship: 1cd5eb75-9a4d-420c-b7a0-3ea233c42679
			defaultHierarchy: LocalDateTable_e8a8847f-0272-4a94-a80d-f74f06c1e3b6.日期层次结构

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition OfficeStatus = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALCI/Shared%20Documents/General/01_Department%20Info/01_Digital%20Huddle/06_KPI/2025/DigitalHuddle/2025%20LCI%20Status%20Calendar.xlsm"), null, true),
				    Source2 = Source{[Item="Table5",Kind="Table"]}[Data],
				    #"Transposed Table" = Table.Transpose(Source2),
				    #"Filtered Rows" = Table.SelectRows(#"Transposed Table", each ([Column4] <> "JIA LCI memebers")),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Filtered Rows", [PromoteAllScalars=true]),
				    #"Filled Down" = Table.FillDown(#"Promoted Headers",{"Column1", "Column2"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filled Down",{{"Column3", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Month"}, {"Column2", "WeekNo"}, {"Column3", "Day"}}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Renamed Columns", {"Month", "WeekNo", "Day"}, "Name", "Color"),
				    #"Inserted Start of Week" = Table.AddColumn(#"Unpivoted Other Columns", "Start of Week", each Date.StartOfWeek([Day],Day.Monday), type date)
				in
				    #"Inserted Start of Week"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

