table 'Access Issue'
	lineageTag: 439e8921-0ba6-4c84-ba53-d7d863319630

	column Title
		dataType: string
		lineageTag: 8f96b4d3-a3bf-4fdd-a23a-09b42df6f31c
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 7a8a99c8-8ac2-4854-8aa6-74c1b713ab7a
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 03119d6f-4175-4fcd-ae1f-9afa1d5c83ec
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column AccessType
		dataType: string
		lineageTag: 2adaea0e-b159-40c5-aacb-2d89f58de8f3
		summarizeBy: none
		sourceColumn: AccessType

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 79fd5573-6628-4313-b650-27d434004e13
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 2174e9d2-0906-4b71-af9c-1704f53159de
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: dateTime
		formatString: General Date
		lineageTag: 04b848aa-19e8-46f9-96d9-1a02b597e60b
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: fa8acabc-f76f-4c01-a9ae-44d8e59cb512
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 1b0216ec-7a03-42ee-900c-c050ad4b1c52
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Attachments
		dataType: string
		lineageTag: 2ba431e6-a0fd-414d-aca5-d0acebd081b0
		summarizeBy: none
		sourceColumn: Attachments

		annotation SummarizationSetBy = Automatic

	column Weekname
		dataType: string
		lineageTag: 4745eaa1-29d0-4bbd-9e3c-c03ca4b3d0cb
		summarizeBy: none
		sourceColumn: Weekname

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: string
		lineageTag: 08bd61c4-2c29-47f4-bcf3-7075e24d2fae
		summarizeBy: none
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = Automatic

	column AccessUserType
		dataType: string
		lineageTag: d47dc258-3877-4d41-bd10-dfa5b5b41c75
		summarizeBy: none
		sourceColumn: AccessUserType

		annotation SummarizationSetBy = Automatic

	column AccessCategory
		dataType: string
		lineageTag: 3b459eef-1f6c-4e88-95f0-f6cc5efa393c
		summarizeBy: none
		sourceColumn: AccessCategory

		annotation SummarizationSetBy = Automatic

	partition 'Access Issue' = m
		mode: import
		source =
				let
				    Source = Security_D,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Category] = "Access Issue")),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Content Type", "Created By", "Modified By", "Penetration Area", "Penetration_Result", "Finished", "Color Tag", "Compliance Asset Id", "Item Child Count", "Folder Child Count", "Label setting", "Retention label", "Retention label Applied"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

