table 'Attendance & Absence(ESPA)'
	lineageTag: 864f1f19-0ba3-4fe5-a23d-ec32b951a158

	column 'Shift 班次'
		dataType: string
		lineageTag: 0373e7fe-540d-4ed3-92e0-f2e8b18d5eb8
		summarizeBy: none
		sourceColumn: Shift 班次

		annotation SummarizationSetBy = Automatic

	column ESPA
		dataType: string
		lineageTag: 4e6e954a-8780-4c2d-9ce0-c2e301a5f21c
		summarizeBy: none
		sourceColumn: ESPA

		annotation SummarizationSetBy = Automatic

	column Area区域
		dataType: string
		lineageTag: 528bd7a1-7fc6-4895-9a01-015bfdb1e03d
		summarizeBy: none
		sourceColumn: Area区域

		annotation SummarizationSetBy = Automatic

	column 'Position 岗位'
		dataType: string
		lineageTag: 5881a213-3833-4d5b-b525-a925675b8f77
		summarizeBy: none
		sourceColumn: Position 岗位

		annotation SummarizationSetBy = Automatic

	column 'Name 姓名'
		dataType: string
		lineageTag: fb7f079c-28c4-422b-8d77-d426acd3eecc
		summarizeBy: none
		sourceColumn: Name 姓名

		annotation SummarizationSetBy = Automatic

	column 'Photo 照片'
		dataType: string
		lineageTag: b66bb8cd-b639-432d-8e2c-32bddb539305
		summarizeBy: none
		sourceColumn: Photo 照片

		annotation SummarizationSetBy = Automatic

	column 'Status 状态'
		dataType: string
		lineageTag: 373c0977-2ae1-49ce-8abe-028341193189
		summarizeBy: none
		sourceColumn: Status 状态

		annotation SummarizationSetBy = Automatic

	column 'Note 备注'
		dataType: string
		lineageTag: 2053d57c-6e65-4c80-acba-bac941adfa36
		summarizeBy: none
		sourceColumn: Note 备注

		annotation SummarizationSetBy = Automatic

	column ShiftStutas = IF('Attendance & Absence(ESPA)'[Shift 班次]="Night Shift 夜班(Yesterday)","🌒","🔆")
		lineageTag: 980d3815-457e-4797-9779-553035bca2af
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Attendance & Absence(ESPA)' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALCI/Shared%20Documents/General/03_BI/01_Project%20List/02.%20Project%20List/09.%20Security%20Digital%20Huddle/Security%20Huddle%20Update.xlsx"), null, true),
				    #"Attendance & Absence(ESPA)_Sheet" = Source{[Item="Attendance & Absence(ESPA)",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Attendance & Absence(ESPA)_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Shift班次", type text}, {"ESPA", type text}, {"Area区域", type text}, {"Position 岗位", type text}, {"Name 姓名", type text}, {"Photo 照片", type any}, {"Status 状态", type text}, {"Note 备注", type any}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Shift班次", "Shift 班次"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

