table 'Night Inspection'
	lineageTag: c3cb79c9-3806-4d37-8cce-d1c77fd68c5e

	column NO
		dataType: int64
		formatString: 0
		lineageTag: 32af374d-1ed4-4105-98ad-9e8be34eeb9f
		summarizeBy: sum
		sourceColumn: NO

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: e94b71ea-586a-42bf-911d-124b2026c05a
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column WHEN
		dataType: dateTime
		formatString: Short Date
		lineageTag: 94f6b960-d953-433f-b83b-6e1039017f52
		summarizeBy: none
		sourceColumn: WHEN

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WHO
		dataType: string
		lineageTag: fdf17a5d-37f9-4e8d-a14d-a29318224942
		summarizeBy: none
		sourceColumn: WHO

		annotation SummarizationSetBy = Automatic

	column WHERE
		dataType: string
		lineageTag: baf0ab13-be94-4a8f-bf80-188da386d91e
		summarizeBy: none
		sourceColumn: WHERE

		annotation SummarizationSetBy = Automatic

	column 'Good Findings (+)'
		dataType: string
		lineageTag: 016deaa7-2460-462f-b3a2-9ef236ea3fec
		summarizeBy: none
		sourceColumn: Good Findings (+)

		annotation SummarizationSetBy = Automatic

	column 'Abnormal Findings (-)'
		dataType: string
		lineageTag: bb95ceab-d944-451c-9d32-68d182b43514
		summarizeBy: none
		sourceColumn: Abnormal Findings (-)

		annotation SummarizationSetBy = Automatic

	column Actions
		dataType: string
		lineageTag: d92aea96-d4c6-4108-867e-6375f54b32d4
		summarizeBy: none
		sourceColumn: Actions

		annotation SummarizationSetBy = Automatic

	column 'Responsible By'
		dataType: string
		lineageTag: 98e89f06-d9a1-4214-a2ca-ca6a5636d772
		summarizeBy: none
		sourceColumn: Responsible By

		annotation SummarizationSetBy = Automatic

	column 'Completion Status'
		dataType: double
		formatString: 0
		lineageTag: 048b302e-cf87-4eba-91fb-fdaf80274c6c
		summarizeBy: sum
		sourceColumn: Completion Status

		annotation SummarizationSetBy = Automatic

	partition 'Night Inspection' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALCI/Shared%20Documents/General/03_BI/01_Project%20List/02.%20Project%20List/09.%20Security%20Digital%20Huddle/Security%20Huddle%20Update.xlsx"), null, true),
				    #"Night Inspection_Sheet" = Source{[Item="Night Inspection",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Night Inspection_Sheet", [PromoteAllScalars=true]),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Promoted Headers", [PromoteAllScalars=true]),
				    #"Added Custom" = Table.AddColumn(#"Promoted Headers1", "Month.1", each Text.Upper(
				    Date.ToText(
				      Date.FromText([MONTH] & " 1, 2020", "en-US"),
				      "MMM",
				      "en-US"
				    )
				  )),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"Photos#(lf) (If Any)", "Photos#(lf) (If Any)_1", "MONTH"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"NO", "Month.1", "WHEN", "WHO", "WHERE", "Good Findings (+)", "Abnormal Findings (-)", "Actions", "Responsible By", "Completion #(lf)Status"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Reordered Columns",{{"Month.1", type text}, {"WHO", type text}, {"WHERE", type text}, {"Good Findings (+)", type text}, {"Abnormal Findings (-)", type text}, {"Actions", type text}, {"Responsible By", type text}, {"NO", Int64.Type}, {"Completion #(lf)Status", Percentage.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Month.1", "Month"}}),
				    #"Add Parsed Column" =
				        Table.AddColumn(
				            #"Renamed Columns",
				            "WHEN_Parsed",
				            each
				                let
				                    raw = [WHEN],
				                    isDate = Value.Is(raw, type date) or Value.Is(raw, type datetime),
				                    cleaned =
				                        if isDate then
				                            raw
				                        else
				                            Text.Replace(
				                                Text.AfterDelimiter(Text.From(raw), ".", {0, RelativePosition.FromStart}),
				                                ".",
				                                " "
				                            ),
				                    parsedDateTime =
				                        if isDate then
				                            if Value.Is(raw, type date) then DateTime.From(raw) else raw
				                        else
				                            DateTime.FromText(cleaned, "en-US")
				                in
				                    DateTime.Date(parsedDateTime),
				            type date
				        ),
				    AddFormattedText = Table.AddColumn(
				            #"Add Parsed Column",
				            "WHEN_Text",
				            each Date.ToText([WHEN_Parsed], "yyyy/M/d"),
				            type text
				        ),
				    #"Reordered Columns1" = Table.ReorderColumns(AddFormattedText,{"NO", "Month", "WHEN", "WHEN_Parsed", "WHO", "WHERE", "Good Findings (+)", "Abnormal Findings (-)", "Actions", "Responsible By", "Completion #(lf)Status"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns1",{"WHEN", "WHEN_Text"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"WHEN_Parsed", "WHEN"}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Renamed Columns1",{{"WHO", Text.Proper, type text}}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Capitalized Each Word", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Filled Down" = Table.FillDown(#"Removed Blank Rows",{"Month", "WHEN", "WHO"})
				in
				    #"Filled Down"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

