table 'Purchase Application'
	lineageTag: 33ad4cc4-fff9-4ff5-81c3-24c5d287fdc6

	column NO
		dataType: int64
		formatString: 0
		lineageTag: 3a16bb43-a1a2-401a-bc03-63d77364f140
		summarizeBy: none
		sourceColumn: NO

		annotation SummarizationSetBy = Automatic

	column WHO
		dataType: string
		lineageTag: 5ec21944-97f3-4598-a360-a9ba0ab550b9
		summarizeBy: none
		sourceColumn: WHO

		annotation SummarizationSetBy = Automatic

	column WHERE
		dataType: string
		lineageTag: 8cc46e7b-54d6-4c71-9bbf-2c83dc30b0b2
		summarizeBy: none
		sourceColumn: WHERE

		annotation SummarizationSetBy = Automatic

	column WHAT
		dataType: string
		lineageTag: 61b8fb1b-65b6-47ad-b651-0383dcbbad75
		summarizeBy: none
		sourceColumn: WHAT

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: string
		lineageTag: 75a0941d-c801-4cc9-8a5b-4c93fad70149
		summarizeBy: none
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column 'Applied Date'
		dataType: string
		lineageTag: 646cfdf0-9e8b-4707-8fa2-8ca4d3d7d91e
		summarizeBy: none
		sourceColumn: Applied Date

		annotation SummarizationSetBy = Automatic

	column OK/No
		dataType: string
		lineageTag: 8875b9f1-1d82-4c14-ae49-820fdc7a8af3
		summarizeBy: none
		sourceColumn: OK/No

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: bcd3f43b-c266-4a88-8e6a-785036364360
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Purchase Status (By Peter)'
		dataType: string
		lineageTag: ce731a72-ed9c-4318-a58e-924983eaa313
		summarizeBy: none
		sourceColumn: Purchase Status (By Peter)

		annotation SummarizationSetBy = Automatic

	column Note
		dataType: string
		lineageTag: 21aeebdf-a7cd-4387-8431-ca227b4eac19
		summarizeBy: none
		sourceColumn: Note

		annotation SummarizationSetBy = Automatic

	column UnifiedDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 37e52e61-3fbb-49be-ac27-94058360fadf
		summarizeBy: none
		sourceColumn: UnifiedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status_light =
			
			SWITCH(
			    TRUE(),
			    'Purchase Application'[Status]="Open","✔️",
			    'Purchase Application'[Status]="Closed","❌")
		lineageTag: ca57bdf3-5cb4-42fc-8895-2f6af5ba09f7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Purchase Application' = m
		mode: import
		source = ```
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALCI/Shared%20Documents/General/03_BI/01_Project%20List/02.%20Project%20List/09.%20Security%20Digital%20Huddle/Security%20Huddle%20Update.xlsx"), null, true),
				    #"Purchase Application_Sheet" = Source{[Item="Purchase Application",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Purchase Application_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"NO", Int64.Type}, {"WHO", type text}, {"WHERE", type any}, {"WHAT", type text}, {"Quantity", type any}, {"Applied Date", type any}, {"OK/No", type text}, {"Status", type text}, {"Purchase Status (By Peter)", type text}, {"Note", type text}}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Changed Type", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Add column"= #"Removed Blank Rows",
				  AddUnifiedDate = Table.AddColumn(
				    #"Removed Blank Rows",
				    "UnifiedDate",
				    each
				      let
				        v = [Applied Date] 
				      in
				        if v = null then
				          null                             // 先处理空值
				        else if Value.Is(v, type date) then
				          v                                // 已经是日期
				        else
				          let
				            txt   = Text.From(v),          // 转成文本
				            parts = Text.Split(txt, ".")   // 拆成 {"2025","7"} 或其它
				          in
				            if List.Count(parts)=2 then
				              #date(
				                Number.FromText(parts{0}),
				                Number.FromText(parts{1}),
				                1
				              )
				            else
				              null,                         // 拆分不对也输出 null
				    type nullable date                     // 整列设为可空日期
				  )
				in
				  AddUnifiedDate
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

