table Security_Q
	lineageTag: 0cd1e9fe-5d44-4f7b-aba2-c4f23e4cf0e2

	column Findings
		dataType: string
		lineageTag: bdd4cc4f-dc4a-4d2e-ac3f-f9cd600dc0d0
		summarizeBy: none
		sourceColumn: Findings

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: 786fdd3f-0341-410b-b9ab-1f22e11d3426
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 548a78ba-a685-4d81-ae16-4575f60ab6ca
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FindingCategory
		dataType: string
		lineageTag: 4629e8e5-e360-4295-a87f-75462ed2059d
		summarizeBy: none
		sourceColumn: FindingCategory

		annotation SummarizationSetBy = Automatic

	column 'ESPA Finding Area '
		dataType: string
		lineageTag: 4bc0cda1-f6d2-4c0d-943e-464a0dc23c02
		summarizeBy: none
		sourceColumn: "ESPA Finding Area "

		annotation SummarizationSetBy = Automatic

	column 'Abnormal Finding Area'
		dataType: string
		lineageTag: 64c5eca1-2b22-43f1-86c4-923966fee08e
		summarizeBy: none
		sourceColumn: Abnormal Finding Area

		annotation SummarizationSetBy = Automatic

	column 'Non ESPA Finding Area'
		dataType: string
		lineageTag: 2748c207-6f49-4334-be7d-fb7034579244
		summarizeBy: none
		sourceColumn: Non ESPA Finding Area

		annotation SummarizationSetBy = Automatic

	column 'Alarm/ False Alarm'
		dataType: string
		lineageTag: 79e5a258-8b95-4457-a7a5-55604f33245e
		summarizeBy: none
		sourceColumn: Alarm/ False Alarm

		annotation SummarizationSetBy = Automatic

	column 'Alarm Type'
		dataType: string
		lineageTag: 1a94b745-a806-46b9-8669-09019322575d
		summarizeBy: none
		sourceColumn: Alarm Type

		annotation SummarizationSetBy = Automatic

	column Where
		dataType: string
		lineageTag: c36b7fda-ec7b-488c-975a-e8f5fe166b3d
		summarizeBy: none
		sourceColumn: Where

		annotation SummarizationSetBy = Automatic

	column 'Photos(Good Finding)'
		dataType: string
		lineageTag: b248cc3b-e985-4549-8479-9e1a7c3030ab
		summarizeBy: none
		sourceColumn: Photos(Good Finding)

		annotation SummarizationSetBy = Automatic

	column 'Good Findings'
		dataType: string
		lineageTag: af52cbd1-9ef5-4c1f-a2c6-76e6223ee17a
		summarizeBy: none
		sourceColumn: Good Findings

		annotation SummarizationSetBy = Automatic

	column 'Abnormal Findings'
		dataType: string
		lineageTag: 86fadb97-607e-4664-b20d-399a1502ca07
		summarizeBy: none
		sourceColumn: Abnormal Findings

		annotation SummarizationSetBy = Automatic

	column 'Photos (Abnormal Findings)'
		dataType: string
		lineageTag: 58ac8fd0-3d88-41ff-9f99-0135326c94da
		summarizeBy: none
		sourceColumn: Photos (Abnormal Findings)

		annotation SummarizationSetBy = Automatic

	column Actions
		dataType: string
		lineageTag: 808f2b91-47e5-46fd-af6b-aacaf0270802
		summarizeBy: none
		sourceColumn: Actions

		annotation SummarizationSetBy = Automatic

	column 'Responsible By'
		dataType: string
		lineageTag: 5b1ee162-ff8f-4296-aae2-ad01623c00b9
		summarizeBy: none
		sourceColumn: Responsible By

		annotation SummarizationSetBy = Automatic

	column Complaint/Appreciation
		dataType: string
		lineageTag: b023db98-0e4b-40ba-8213-a2c969977b1b
		summarizeBy: none
		sourceColumn: Complaint/Appreciation

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 7febe670-2f8d-487c-a728-8a2be101783a
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Associated files'
		dataType: string
		lineageTag: 1b11ff4d-a702-45c2-be7a-01c2844dc59b
		summarizeBy: none
		sourceColumn: Associated files

		annotation SummarizationSetBy = Automatic

	column 'Color Tag'
		dataType: string
		lineageTag: 3b10fb68-1988-4899-a7bf-0b3822d10cde
		summarizeBy: none
		sourceColumn: Color Tag

		annotation SummarizationSetBy = Automatic

	column 'Compliance Asset Id'
		dataType: string
		lineageTag: d5697a75-5e20-400b-aa09-97ffc0206aa9
		summarizeBy: none
		sourceColumn: Compliance Asset Id

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: fd43a1ca-2899-4790-84a9-f30494e20d21
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: f255fdd3-3ca4-428f-a03e-adaa6f7c6316
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Assigned to'
		dataType: string
		lineageTag: ced1017b-6513-46f9-b5ee-30f9b10da436
		summarizeBy: none
		sourceColumn: Assigned to

		annotation SummarizationSetBy = Automatic

	column 'Related issue'
		dataType: string
		lineageTag: ef7bb9e7-3f29-4145-9000-d4f5fa1ab4bb
		summarizeBy: none
		sourceColumn: Related issue

		annotation SummarizationSetBy = Automatic

	column CorA_Area
		dataType: string
		lineageTag: 6b0df0d0-9465-459d-89f7-5cd512049c63
		summarizeBy: none
		sourceColumn: CorA_Area

		annotation SummarizationSetBy = Automatic

	column 'Content Type'
		dataType: string
		lineageTag: 66922557-1f2f-42c7-a833-2f9c4bcae794
		summarizeBy: none
		sourceColumn: Content Type

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: dateTime
		formatString: General Date
		lineageTag: b59f6a32-13d8-42ed-8bb4-81faef83beeb
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

	column 'Modified By'
		dataType: string
		lineageTag: 488470f6-eafd-4193-9325-ba415ac862f1
		summarizeBy: none
		sourceColumn: Modified By

		annotation SummarizationSetBy = Automatic

	column Edit
		dataType: string
		lineageTag: b6ce217c-ede8-4062-b3ea-ce18a79bc76e
		summarizeBy: none
		sourceColumn: Edit

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 595baf7c-733f-4909-8340-6a173405c8cc
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Item Child Count'
		dataType: string
		lineageTag: e41928d5-2e82-4f3a-8297-7a226a597396
		summarizeBy: none
		sourceColumn: Item Child Count

		annotation SummarizationSetBy = Automatic

	column 'Folder Child Count'
		dataType: string
		lineageTag: 2d605aef-5c83-486b-947c-0ad2a13d014c
		summarizeBy: none
		sourceColumn: Folder Child Count

		annotation SummarizationSetBy = Automatic

	column 'Label setting'
		dataType: string
		lineageTag: 1432ffc3-6d3a-4648-b8e1-670256e37228
		summarizeBy: none
		sourceColumn: Label setting

		annotation SummarizationSetBy = Automatic

	column 'Retention label'
		dataType: string
		lineageTag: c613a31b-8f7e-4708-8201-8de76d1f93a2
		summarizeBy: none
		sourceColumn: Retention label

		annotation SummarizationSetBy = Automatic

	column 'Retention label Applied'
		dataType: string
		lineageTag: b12974a6-e7d0-428d-b3a0-39c311aeb151
		summarizeBy: none
		sourceColumn: Retention label Applied

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: string
		lineageTag: a519edab-b135-4bbc-a40a-7aa3e3c011cc
		summarizeBy: none
		sourceColumn: Weekday

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: string
		lineageTag: 62567f14-15cc-4398-8e49-9e938b6c1639
		summarizeBy: none
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = Automatic

	partition Security_Q = m
		mode: import
		source =
				let
				    Source = SharePoint.Tables("https://legogroup.sharepoint.com/sites/JIALCI/", [Implementation="2.0", ViewMode="All"]),
				    #"21b3cb6b-3b39-42ef-9f93-ce3b70300f05" = Source{[Id="21b3cb6b-3b39-42ef-9f93-ce3b70300f05"]}[Items],
				    #"Removed Columns" = Table.RemoveColumns(#"21b3cb6b-3b39-42ef-9f93-ce3b70300f05",{"Version", "Label applied by", "Item is a Record", "App Created By", "App Modified By", "Created By"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"Date", type date}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Weekday", each Date.ToText([Date], "ddd", "en-US")),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "DayOfMonth", each Date.Day([Date]))
				in
				    #"Added Custom1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

