table 'Visitors Today'
	lineageTag: 63af9e0a-ea9f-461e-8daa-87c8c6dd19cb

	column Time
		dataType: string
		lineageTag: 6434c4ac-7551-48a7-aa27-c89da4d92117
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

	column 'Visitors From'
		dataType: string
		lineageTag: f60566a9-5c2b-432d-ada5-f8a1498a2079
		summarizeBy: none
		sourceColumn: Visitors From

		annotation SummarizationSetBy = Automatic

	column 'Visitor Qty '
		dataType: string
		lineageTag: 8cb0185f-682a-447a-b5d2-110ffc92e4c0
		summarizeBy: none
		sourceColumn: "Visitor Qty "

		annotation SummarizationSetBy = Automatic

	column 'Location '
		dataType: string
		lineageTag: a7667347-fbe9-4174-8dc7-2fbb26f199d8
		summarizeBy: none
		sourceColumn: "Location "

		annotation SummarizationSetBy = Automatic

	column 'Visting Area'
		dataType: string
		lineageTag: 0c01fa05-128a-454e-863b-9fefecc9a11e
		summarizeBy: none
		sourceColumn: Visting Area

		annotation SummarizationSetBy = Automatic

	column 'Security Request'
		dataType: string
		lineageTag: 991f9c71-f97c-4b1b-b7d6-c971779a179c
		summarizeBy: none
		sourceColumn: Security Request

		annotation SummarizationSetBy = Automatic

	column 'LEGO Department'
		dataType: string
		lineageTag: 06d92d77-0352-4437-b525-18134890800b
		summarizeBy: none
		sourceColumn: LEGO Department

		annotation SummarizationSetBy = Automatic

	column N
		dataType: int64
		formatString: 0
		lineageTag: 9603ba7c-7a17-41db-86c5-1e701d761e00
		summarizeBy: sum
		sourceColumn: N

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: ee81e4aa-0557-4bb6-89c0-c4a91ee61b15
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Enter Position'
		dataType: string
		lineageTag: 801f67fd-4ead-4b6f-8e43-16b132d96c4d
		summarizeBy: none
		sourceColumn: Enter Position

		annotation SummarizationSetBy = Automatic

	column 'ESPA Escort'
		dataType: string
		lineageTag: 0103310c-d21d-4bdd-a92f-a28003cb51c1
		summarizeBy: none
		sourceColumn: ESPA Escort

		annotation SummarizationSetBy = Automatic

	column 'Non-ESPA Escort'
		dataType: string
		lineageTag: afe05348-c377-46c3-b789-b6927a407a32
		summarizeBy: none
		sourceColumn: Non-ESPA Escort

		annotation SummarizationSetBy = Automatic

	column 'LEGO HOST'
		dataType: string
		lineageTag: 8bf5dec3-d1b1-484e-8f7f-bab8f4488b18
		summarizeBy: none
		sourceColumn: LEGO HOST

		annotation SummarizationSetBy = Automatic

	column ' Contact PersonEleanor Xiang :13252319198'
		dataType: string
		lineageTag: cdb925ad-4510-483a-a1bb-ef27320c4dff
		summarizeBy: none
		sourceColumn: " Contact PersonEleanor Xiang :13252319198"

		annotation SummarizationSetBy = Automatic

	partition 'Visitors Today' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALCI/Shared%20Documents/General/03_BI/01_Project%20List/02.%20Project%20List/09.%20Security%20Digital%20Huddle/Security%20Huddle%20Update.xlsx"), null, true),
				    #"Visitor(s) Today_Sheet" = Source{[Item="Visitor(s) Today",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(#"Visitor(s) Today_Sheet",1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Removed Blank Rows" = Table.SelectRows(#"Promoted Headers", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Removed Blank Rows", "Date", "Date - Copy"),
				    #"Trimmed Text" = Table.TransformColumns(Table.TransformColumnTypes(#"Duplicated Column", {{"Date - Copy", type text}}, "zh-CN"), {{"Date - Copy", Text.Trim, type text}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Trimmed Text", "Date - Copy", Splitter.SplitTextByEachDelimiter({"-"}, QuoteStyle.Csv, false), {"Date - Copy.1", "Date - Copy.2"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Split Column by Delimiter",{"Date - Copy.2"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Date - Copy.1", "DDate"}}),
				
				    #"Has 4 Digit Year" = Table.AddColumn(#"Renamed Columns", "HasYear",
				        each Text.Length(Text.Select([DDate], {"0".."9"})) >= 4, type logical),
				
				    #"SlashToSpace" = Table.AddColumn(#"Has 4 Digit Year", "Norm2",
				        each Text.Replace([DDate], "/", " "), type text),
				
				    CurrentYearText = Text.From(Date.Year(DateTime.LocalNow())),
				    #"Add Year If Missing" = Table.AddColumn(#"SlashToSpace", "NormWithYear",
				        each if [HasYear] then Text.Trim([Norm2]) else Text.Trim([Norm2] & " " & CurrentYearText), type text),
				
				    #"Try Parse NormWithYear" = Table.AddColumn(#"Add Year If Missing", "Parsed",
				        each try Date.FromText([NormWithYear], "en-US") otherwise null, type nullable date),
				
				    #"Fallback Parse Original" = Table.AddColumn(#"Try Parse NormWithYear", "ParsedFallback",
				        each if [Parsed] = null then (try Date.FromText([Date]) otherwise null) else [Parsed], type nullable date),
				
				    #"Final Date Column" = Table.AddColumn(#"Fallback Parse Original", "FinalDate",
				        each if [Parsed] <> null then [Parsed] else [ParsedFallback], type nullable date),
				    #"Changed Type" = Table.TransformColumnTypes(#"Final Date Column", {{"FinalDate", type date}}),
				    colsToKeep = List.Distinct(List.Combine({Table.ColumnNames(#"Removed Blank Rows"), {"FinalDate"}})),
				    #"Keep Original + Final" = Table.SelectColumns(#"Changed Type", List.Intersect({Table.ColumnNames(#"Changed Type"), colsToKeep})),
				    #"Reordered Columns" = Table.ReorderColumns(#"Keep Original + Final",{"N", "FinalDate", "Time", "Visitors From", "Visitor Qty ", "Location ", "Visting Area", "Enter Position", "ESPA Escort", "Non-ESPA Escort", "Security Request", "LEGO HOST", " Contact Person#(lf)Eleanor Xiang :13252319198", "LEGO Department"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns",{"Date"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"FinalDate", "Date"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"N", Int64.Type}}),
				    #"Trimmed Text1" = Table.TransformColumns(#"Changed Type1",{{"LEGO HOST", Text.Trim, type text}, {" Contact Person#(lf)Eleanor Xiang :13252319198", Text.Trim, type text}, {"LEGO Department", Text.Trim, type text}})
				in
				    #"Trimmed Text1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

