table Productivity_PFP
	lineageTag: 34277b8b-888b-4dad-ac0a-950d28163af1

	column IL
		dataType: string
		lineageTag: 64788477-ab60-47da-a7d8-4a4a50701520
		summarizeBy: none
		sourceColumn: IL

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: bb4988f4-d5e1-41ec-abdf-52c8f77bc195
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: c8de539e-17ec-4bf8-91c0-0dcecb8b3360
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 95d30344-003c-43d8-bb44-0468349c8644
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Date created'
		dataType: string
		lineageTag: 322d02da-edb9-40fa-b8d3-0cf70a8cb946
		summarizeBy: none
		sourceColumn: Date created

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 47d4f9f9-32c2-4ef8-8518-62353a0901b5
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column 'Value Type'
		dataType: string
		lineageTag: 3c87cdae-6516-4054-b751-4fad6f7ac6f8
		summarizeBy: none
		sourceColumn: Value Type

		annotation SummarizationSetBy = Automatic

	partition Productivity_PFP = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows([]),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"7c90095b-31de-43da-b11e-e3c19e33be7d" = Workspaces{[workspaceId="7c90095b-31de-43da-b11e-e3c19e33be7d"]}[Data],
				    #"8b87b6cf-63ec-405d-9c19-2ab933c27890" = #"7c90095b-31de-43da-b11e-e3c19e33be7d"{[dataflowId="8b87b6cf-63ec-405d-9c19-2ab933c27890"]}[Data],
				    pfp_ = #"8b87b6cf-63ec-405d-9c19-2ab933c27890"{[entity="pfp",version=""]}[Data],
				    #"Added Custom" = Table.AddColumn(pfp_, "Key", each [Month Name] &"-"& [IL LEVEL]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"Date created"}),
				    #"Added Custom1" = Table.AddColumn(#"Removed Columns", "Value Type", each "PFP"),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom1",{{"IL LEVEL", "IL"}, {"TECHNOLOGY", "Area"}, {"Month Name", "Date created"}, {"PfP", "Value"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

