table 'Table_IL key'
	lineageTag: 31df5e6e-46e3-42ea-858c-95fc3530907e

	column IL
		dataType: string
		lineageTag: d6664d70-8bb3-40a8-aec2-3149a73df2c1
		summarizeBy: none
		sourceColumn: IL

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: b5595308-e065-4d80-9007-6e76a9a5a0c9
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 5bc9eea4-588d-4fa1-b954-1c6188cff7a1
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 8e5c202b-6f98-4792-bc26-6f42ee22b464
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	partition 'Table_IL key' = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows([]),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"7c90095b-31de-43da-b11e-e3c19e33be7d" = Workspaces{[workspaceId="7c90095b-31de-43da-b11e-e3c19e33be7d"]}[Data],
				    #"8b87b6cf-63ec-405d-9c19-2ab933c27890" = #"7c90095b-31de-43da-b11e-e3c19e33be7d"{[dataflowId="8b87b6cf-63ec-405d-9c19-2ab933c27890"]}[Data],
				    Overview_ = #"8b87b6cf-63ec-405d-9c19-2ab933c27890"{[entity="Overview",version=""]}[Data],
				    #"Added Custom" = Table.AddColumn(Overview_, "Key", each [Month]&"-"&[IL])
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

