table Sales
	lineageTag: 94d3ea3b-4449-4e27-903d-c961f1df5413

	measure 'Sales Amount' = SUMX ( Sales, Sales[Quantity] * Sales[Net Price] )
		formatString: #,0
		lineageTag: 7c5f9a14-3465-43ab-b1e5-aeb03f4fe8ad

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Cost' = SUMX ( Sales, Sales[Quantity] * Sales[Unit Cost] )
		formatString: #,0.00
		lineageTag: 416604ca-8ec2-48fb-97e3-568ef1a0c264

		changedProperty = FormatString

	measure Margin = [Sales Amount] - [Total Cost]
		formatString: #,0.00
		lineageTag: e22dbc08-3844-485a-96d6-625d9d77e004

		changedProperty = FormatString

	measure 'Margin %' = DIVIDE ( [Margin], [Sales Amount] )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 78f2291d-1076-4202-b7bc-8d5dcd28f612

		changedProperty = FormatString

	measure 'Disctinct Product Category' = DISTINCTCOUNT('Product'[Category])
		formatString: 0
		lineageTag: 2d2fd8c2-c60d-4ead-a190-afb6e3334cef

	measure Measure
		lineageTag: eb15c39d-c3f6-4409-bea9-c723f5b721c9

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure Sales_rk = ```
			
			    var rkValue = [Parameter Value]
			    var SalesAmt = [Sales Amount]
			    var IsOtherSelected = SELECTEDVALUE('ExtendProduct'[Product Name])= "Others"
			    var RanksSales = RANKX( ALLSELECTED('ExtendProduct'[Product Name]),[Sales Amount])
			    var Rk = IF(RanksSales<=rkValue,RanksSales,RanksSales+1)
			    var AdjustedRank  = IF( 
			                    IsOtherSelected,
			                     rkValue+1,
			                    Rk
			                    )
			RETURN
			    AdjustedRank
			```
		formatString: 0
		lineageTag: 66aeb47b-5652-4e78-bed7-c6ad0861d874

	measure VisbleProduct = INT([Sales_rk]<=[Parameter Value]+1)
		formatString: 0
		lineageTag: ed3e8b7f-44ce-452f-a007-95ec65cb2706

	measure Top3Sales =
			
			var tTop = TOPN(3,ALLSELECTED('Product'[Product Name]),[Sales Amount],DESC)
			var res = CALCULATE([Sales Amount],KEEPFILTERS(tTop))
			
			RETURN
			    res
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2a245cd7-1b44-4550-b86d-45108d4038f8

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Top3SalesX = ```
			
			var top3Table = TOPN([TopN Value], ALLSELECTED('Product'[Product Name]),[Sales Amount],DESC)
			 //return top3 table 
			var TOp3Sales = CALCULATE([Sales Amount], KEEPFILTERS( top3Table) ) 
			// sum top 3 table  , keepfilter = crossjoin
			var OtherSales = [Sales Amount] -TOp3Sales
			var res  = IF(ISINSCOPE('Product'[Product Name]),TOp3Sales, FORMAT(OtherSales,"#,#") & UNICHAR(10) &  FORMAT([Sales Amount],"#,#" ))
			RETURN
			    res
			```
		lineageTag: 4ea98f3b-1c3b-4845-85df-bfc647edf52f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure IsBrandInScope = ```
			
			var  pN =    ISINSCOPE('Product'[Product Name])
			var  Brd = ISINSCOPE('Product'[Brand])
			RETURN  
			    Brd
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 55ceca21-4052-4161-9e2d-d23dacb95517

	measure IsProductNameInScope_ = ```
			
			var  pN =    ISINSCOPE('Product'[Product Name])
			RETURN  
			    pN
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 61c2bc7c-507b-4583-ba01-1d766232968a

	measure Label = ```
			
			IF([Top3Sales]>0,
			    IF( 
			        ISINSCOPE('Product'[Product Name]),
			         SELECTEDVALUE('Product'[Product Name]),
			         "Others" & UNICHAR(10) & "Total"
			        ),
			        BLANK()
			 )
			```
		lineageTag: 1e24222b-66db-4641-ad23-b638599da18e

	column 'Order Number'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 91ea6a29-4cac-4426-9100-5736937552bf
		summarizeBy: none
		sourceColumn: Order Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Line Number'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 45bd733b-90c9-4ecc-93d6-37528e2e27b4
		summarizeBy: none
		sourceColumn: Line Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Order Date'
		dataType: dateTime
		isHidden
		formatString: mm/dd/yyyy
		lineageTag: 64b1d016-32bc-4c20-80d7-a5adc3b9ae88
		summarizeBy: none
		sourceColumn: Order Date

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Delivery Date'
		dataType: dateTime
		isHidden
		formatString: mm/dd/yyyy
		lineageTag: fb541e07-fdfb-40c9-9166-29777f049df4
		summarizeBy: none
		sourceColumn: Delivery Date

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b35afdc7-615a-4e88-8c36-36c10285f310
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f917bacb-2013-409d-9d94-8b40068bc9a7
		summarizeBy: none
		sourceColumn: StoreKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f011ea83-0d14-41e5-a9f2-8d532338586f
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c8ca10d3-f54d-4c5d-b5ef-da854e2d7973
		summarizeBy: none
		sourceColumn: Quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Unit Price'
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: 8c2ee660-1f97-48df-a30b-9e6818ed5be9
		summarizeBy: none
		sourceColumn: Unit Price

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = User

	column 'Net Price'
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: 690e56a1-1bb6-4aa8-83bc-2b81fa8e4bf7
		summarizeBy: none
		sourceColumn: Net Price

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = User

	column 'Unit Cost'
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: 07c65c15-9e35-47c1-bbab-9cca274818c7
		summarizeBy: none
		sourceColumn: Unit Cost

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = User

	column 'Currency Code'
		dataType: string
		isHidden
		lineageTag: af1aa82f-8a7e-4d57-9da8-8d64994488a5
		summarizeBy: none
		sourceColumn: Currency Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Exchange Rate'
		dataType: double
		isHidden
		formatString: 0.0000
		lineageTag: 7ddca17e-170a-4c4d-aa29-37f19394e838
		summarizeBy: none
		sourceColumn: Exchange Rate

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = User

	partition Sales-4929449f-be0b-48cf-a44e-c644698415ba = m
		mode: import
		source =
				let
				    Source = Sql.Databases("Demo"),
				    #"Contoso" = Source{[Name="Contoso V2 1M"]}[Data],
				    dbo_Sales = #"Contoso"{[Schema="dbo",Item="Sales"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_Sales,{{"Quantity", Int64.Type}, {"Unit Price", Currency.Type}, {"Net Price", Currency.Type}, {"Unit Cost", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

