table DetailedProjects
	lineageTag: d68df17a-b4f0-4db5-a6ff-2e79beca0835

	column Category
		dataType: string
		lineageTag: c42710e2-be26-462d-b6ed-0a74e3fbf59c
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'ID Tracker'
		dataType: string
		lineageTag: 0b883308-a4cd-4cce-81d5-32c890c87988
		summarizeBy: none
		sourceColumn: ID Tracker

		annotation SummarizationSetBy = Automatic

	column Initiatives
		dataType: string
		lineageTag: d0ed7058-aa23-4735-98f0-5d54643c967b
		summarizeBy: none
		sourceColumn: Initiatives

		annotation SummarizationSetBy = Automatic

	column Comments
		dataType: string
		lineageTag: 21cfb8f6-6681-4a8c-9543-fda372da0879
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	column Status = ```
			
			VAR ActualMonth = WEEKNUM([SAT Actual])
			VAR PlanMonth = WEEKNUM([SAT Plan])
			VAR CurrentMonth = WEEKNUM(TODAY())
			VAR fx = 
			    IF(
			        ISBLANK('DetailedProjects'[SAT Plan]), "🟡", 
			        IF(
			            ISBLANK(ActualMonth),              
			                IF(CurrentMonth <= PlanMonth, "🟢", "🔴"),
			                IF(ActualMonth <= PlanMonth, "🟢", "🔴")
			        )
			    )
			RETURN
			    fx
			```
		lineageTag: cc73df64-a2b9-4d1f-9433-7e379096b463
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Site
		dataType: string
		lineageTag: 9ac4fb59-2ab5-4174-a4db-0f527f2bd7a2
		summarizeBy: none
		sourceColumn: Site

		annotation SummarizationSetBy = Automatic

	column 'SAT Plan'
		dataType: dateTime
		formatString: m/d/yyyy
		lineageTag: da2b9d37-cce9-4237-b5ae-2089d7988270
		summarizeBy: none
		sourceColumn: SAT Plan

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'SAT Actual'
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 2e5ebeeb-7146-4411-b7a4-6b0e03d745d0
		summarizeBy: none
		sourceColumn: SAT Actual

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 5cc18fb7-d525-4897-b1e5-87d9c6b6532c
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8a0c5d41-38f5-49fe-98bc-e0e730d63045
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Created
		dataType: dateTime
		formatString: Long Date
		lineageTag: 965174c1-688e-4e84-8c3b-edb37b6b46e4
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'SAT Lead'
		dataType: string
		lineageTag: d5a751e0-ce57-450b-a7c1-13d5ebcbc02e
		summarizeBy: none
		sourceColumn: SAT Lead

		annotation SummarizationSetBy = Automatic

	column 'Implement Lead'
		dataType: string
		lineageTag: a2166765-3c25-4b4f-8fd0-7a0d4e7f9330
		summarizeBy: none
		sourceColumn: Implement Lead

		annotation SummarizationSetBy = Automatic

	column UpdateOn
		dataType: dateTime
		formatString: m/d/yy
		lineageTag: 5b2cf55a-0969-413d-9508-41b1b8a9fd75
		summarizeBy: none
		sourceColumn: UpdateOn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column SATPlanWk = WEEKNUM('DetailedProjects'[SAT Plan])
		formatString: 0
		lineageTag: 0955a888-8332-45f4-8b41-3f22b2e491ea
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column WkActual = WEEKNUM(DetailedProjects[SAT Actual])
		formatString: 0
		lineageTag: b32b5326-cb69-4eb5-ab8b-719b9cbe8551
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column UpdatedOnWeek = WEEKNUM('DetailedProjects'[UpdateOn])
		formatString: 0
		lineageTag: 09e3dae6-a04e-4fc2-82ff-c0b1efe783cf
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Todaywk = WEEKNUM(TODAY(),21)
		formatString: 0
		lineageTag: 907a3902-f1f6-4827-ab44-df8f7da4d225
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition DetailedProjects = m
		mode: import
		source =
				let
				    Source = SharePoint.Tables("https://legogroup.sharepoint.com/sites/globalprocessingwheel", [Implementation="2.0", ViewMode="All"]),
				    #"57a704bc-26c2-4675-8669-afbe3cc3b773" = Source{[Id="57a704bc-26c2-4675-8669-afbe3cc3b773"]}[Items],
				    #"Changed Type" = Table.TransformColumnTypes(#"57a704bc-26c2-4675-8669-afbe3cc3b773",{{"SAT Plan", type date}, {"SAT Actual", type date}, {"UpdateOn", type date}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Created By", "Modified By", "Version", "Attachments", "Edit", "Type", "Item Child Count", "Folder Child Count", "Label setting", "Retention label", "Retention label Applied", "Label applied by", "Item is a Record", "App Created By", "App Modified By", "Content Type", "Compliance Asset Id", "Color Tag"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"Modified", type date}, {"Created", type date}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

