table Customer
	lineageTag: 65b309cf-ba86-4432-84fa-750593859736

	measure PastandSelectedSales = ```
			
			
			var SelectedMonth = DATESBETWEEN('SlicerTbl'[Date],STARTOFMONTH(SlicerTbl[Date]),ENDOFMONTH(SlicerTbl[Date]))
			var pMss = PMs[PMs Value]
			var past3Month = EOMONTH(MAX(SlicerTbl[Date]),-pMss+1)
			var StartDayPat3Month = EOMONTH(past3Month,-1)+1
			var Past3SelecedMonth =
			    DATESBETWEEN(
			        SlicerTbl[Date],
			        StartDayPat3Month,
			        past3Month
			    )
			
			var TwoSingleMonth = UNION(SelectedMonth,Past3SelecedMonth)
			
			var TwoContinousMonths = DATESBETWEEN('Date'[Date],StartDayPat3Month,ENDOFMONTH(SlicerTbl[Date]))
			var MaxSales = 
			        CALCULATE(
			            MAXX(
			                ALLSELECTED('Date'[Month]),
			                [Sales Amount]
			            ),
			            TwoContinousMonths
			        )
			
			var res = 
			    CALCULATE(
			        [Sales Amount],
			        KEEPFILTERS(
			            TREATAS(TwoSingleMonth,'Date'[Date])
			        )
			    )
			        
			RETURN
			    IF(res,MaxSales*1.3)
			    
			```
		formatString: "¥"#,0.###############;"¥"-#,0.###############;"¥"#,0.###############
		lineageTag: 9c87ac39-e408-4d21-a40e-3ebad79770f3

		annotation PBI_FormatHint = {"currencyCulture":"zh-CN"}

	measure allMax = ```
			
			
			var SelectedMonth = DATESBETWEEN('SlicerTbl'[Date],STARTOFMONTH(SlicerTbl[Date]),ENDOFMONTH(SlicerTbl[Date]))
			var pMss = PMs[PMs Value]
			var past3Month = EOMONTH(MAX(SlicerTbl[Date]),-pMss+1)
			var StartDayPat3Month = EOMONTH(past3Month,-1)+1
			var Past3SelecedMonth =
			    DATESBETWEEN(
			        SlicerTbl[Date],
			        StartDayPat3Month,
			        past3Month
			    )
			
			var TwoSingleMonth = UNION(SelectedMonth,Past3SelecedMonth)
			
			var TwoContinousMonths = DATESBETWEEN('Date'[Date],StartDayPat3Month,ENDOFMONTH(SlicerTbl[Date]))
			var MaxSales = 
			        CALCULATE(
			            MAXX(
			                ALLSELECTED('Date'[Month]),
			                [Sales Amount]
			            ),
			            TwoContinousMonths
			        )
			
			var res = 
			    CALCULATE(
			        [Sales Amount],
			        KEEPFILTERS(
			            TREATAS(TwoContinousMonths,'Date'[Date])
			        )
			    )
			        
			RETURN
			    IF(res,MaxSales*1.3)
			```
		formatString: #,0.00
		lineageTag: a8b83762-3cc9-4585-ac0d-2430a0fce692

	measure UpperBound =
			
			IF([PastandSelectedSales]>0,
			   [Sales Amount]
			)
		formatString: "¥"#,0.###############;"¥"-#,0.###############;"¥"#,0.###############
		lineageTag: 50838b67-1f22-42af-8c4d-f434f240d035

		annotation PBI_FormatHint = {"currencyCulture":"zh-CN"}

	measure Label = ```
			
			
			var res= 
			    IF(
			        [PastandSelectedSales]>0,
			        [Sales Amount]
			    )
			
			RETURN
			    FORMAT(res,"#,0$")
			```
		lineageTag: 4eb80cba-5c24-470c-bc89-f67baccfdbd8

	column CustomerKey
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: 1bec37f7-715f-48d0-8d5b-e8f9db0a9eea
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Name
		dataType: string
		lineageTag: 8baa5636-2a72-44bc-b991-83c021cf4179
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'Birth Date'
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: e2793b41-4089-4fe9-8329-2f3e08358fc8
		summarizeBy: none
		sourceColumn: Birth Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Marital Status'
		dataType: string
		isHidden
		lineageTag: 5459c55b-0e28-4324-ac35-1388e90690de
		summarizeBy: none
		sourceColumn: Marital Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 3debd903-2957-440c-91c0-615c5f4ece9e
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Yearly Income'
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: c3b745aa-092c-46e9-9b7f-ff4598aae0d6
		summarizeBy: none
		sourceColumn: Yearly Income

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Total Children'
		dataType: int64
		isHidden
		lineageTag: 0d291d2c-72b7-4b50-a13e-32195299284c
		summarizeBy: none
		sourceColumn: Total Children

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Children At Home'
		dataType: int64
		isHidden
		lineageTag: 3a87bd93-2893-4777-8f6f-f1cb69993cbb
		summarizeBy: none
		sourceColumn: Children At Home

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Education
		dataType: string
		lineageTag: 4973e7d6-53e8-4988-aaa9-e8b6747d9a50
		summarizeBy: none
		sourceColumn: Education

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: 34bd1c21-ca51-49ed-b758-a99f7487787a
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column Continent
		dataType: string
		isHidden
		lineageTag: 75116c72-dc5c-476a-aa8a-6386600ddfbf
		summarizeBy: none
		sourceColumn: Continent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		isHidden
		lineageTag: 5679273d-be38-4d86-b77f-ee5361933f90
		summarizeBy: none
		sourceColumn: City

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		isHidden
		lineageTag: cf41deed-fe7b-41f9-8944-82510c6776df
		summarizeBy: none
		sourceColumn: State

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Address Line 1'
		dataType: string
		isHidden
		lineageTag: 64a14128-8424-4f61-89c9-2920fe14d0ab
		summarizeBy: none
		sourceColumn: Address Line 1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Customer Type'
		dataType: string
		isHidden
		lineageTag: f0068c0c-af8b-49b6-8160-c45aaa4dbdc6
		summarizeBy: none
		sourceColumn: Customer Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CountryRegion
		dataType: string
		isHidden
		lineageTag: 1a102a3a-7646-4199-876b-f84d453b8b82
		summarizeBy: none
		sourceColumn: CountryRegion

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	hierarchy Geography
		lineageTag: 730f233e-9aa4-4905-a561-062c84f3ece4

		level Continent
			lineageTag: 06fc1072-e161-4c2c-b2fb-e3ff11bb8025
			column: Continent

		level Country
			lineageTag: 79b52f3a-765a-431b-80ff-de6d89366194
			column: CountryRegion

		level State
			lineageTag: f08db78b-2349-4d51-8b96-e96f16d41816
			column: State

		level City
			lineageTag: cd284695-340c-4e13-9222-cba257f86951
			column: City

	partition 'DaxBook Customer' = m
		mode: import
		source =
				let
				    Source = Sql.Database("Demo", "ContosoRetailDW"),
				    DaxBook_Customer = Source{[Schema="DaxBook",Item="Customer"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(DaxBook_Customer,{"GeographyKey", "Title", "Customer Code", "Phone", "Address Line 2", "Date First Purchase", "House Ownership", "Cars Owned", "Company Name"})
				in
				    #"Removed Columns"

		annotation IsQueryEditorUsed = False

		annotation QueryEditorSerialization

		annotation TableWidgetSerialization

	annotation _TM_ExtProp_QueryDefinition = SELECT * FROM [Customer]

	annotation _TM_ExtProp_DbTableName = 63

	annotation IsQueryEditorUsed = False

	annotation QueryEditorSerialization

	annotation TableWidgetSerialization

	annotation DataMarketWebBaseUrl

	annotation DataMarketWebQueryUrl

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

