table Sales
	lineageTag: 7a84fe45-4542-41ce-a169-919ad9a7f587

	measure 'Sales Amount' = SUMX ( Sales, Sales[Quantity] * Sales[Net Price] )
		formatString: #,0.00
		lineageTag: e9e7e5a2-5ec5-419b-92e5-daeb2e94ae62

	measure '# Sales' = COUNTROWS ( Sales )
		formatString: #,0
		lineageTag: 0968cf37-b25c-43f3-9fe4-baa7bea0b39d

	measure '# Customers' = DISTINCTCOUNT( Sales[CustomerKey] )
		formatString: #,0
		lineageTag: 580e8fda-96a1-49d5-bc04-c96a2830a5ac

	column ProductKey
		dataType: int64
		isHidden
		lineageTag: 528033a4-1c8c-4d91-ae41-387ba0306b94
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CustomerKey
		dataType: int64
		isHidden
		lineageTag: aaceed55-d5d3-43bd-b26b-e79452f85da8
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderDateKey
		dataType: int64
		isHidden
		lineageTag: d8ac67a3-f137-4949-ae01-61b5c1cf3570
		summarizeBy: count
		sourceColumn: OrderDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Date'
		dataType: dateTime
		isHidden
		lineageTag: 34e15019-eef9-4a2a-b081-f3d2799e2df2
		summarizeBy: none
		sourceColumn: Order Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Delivery Date'
		dataType: dateTime
		isHidden
		lineageTag: 5ecf948c-1ce1-43bd-b0d6-6d7af15704c4
		summarizeBy: none
		sourceColumn: Delivery Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Order Number'
		dataType: string
		isHidden
		lineageTag: f68de047-f345-4ee3-addf-121ebf0830e6
		summarizeBy: none
		sourceColumn: Order Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Order Line Number'
		dataType: int64
		isHidden
		lineageTag: fa360676-319f-47ae-9ccc-800355dedefa
		summarizeBy: none
		sourceColumn: Order Line Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: ba8d975e-a625-4b66-bc67-86f3d9d4eeea
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: d80f5c7a-02e1-4073-91a3-f4f84ab878f9
		summarizeBy: none
		sourceColumn: Unit Price

		annotation SummarizationSetBy = User

	column 'Unit Discount'
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: 1ec6a821-252d-4f02-b7a1-8d0ebbea3ab9
		summarizeBy: none
		sourceColumn: Unit Discount

		annotation SummarizationSetBy = User

	column 'Unit Cost'
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: 421bb59d-9c85-4d49-a028-98cec838131d
		summarizeBy: none
		sourceColumn: Unit Cost

		annotation SummarizationSetBy = User

	column 'Net Price'
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: fda274ad-dac2-4130-8f4e-ea234cc9e224
		summarizeBy: none
		sourceColumn: Net Price

		annotation SummarizationSetBy = User

	partition 'DaxBook Sales' = m
		mode: import
		source =
				let
				    Source = Sql.Database("Demo", "ContosoRetailDW"),
				    DaxBook_Sales = Source{[Schema="DaxBook",Item="Sales"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(DaxBook_Sales,{"OnlineSalesKey", "Due Date", "DueDateKey", "DeliveryDateKey", "CurrencyKey", "PromotionKey", "StoreKey"})
				in
				    #"Removed Columns"

		annotation IsQueryEditorUsed = False

		annotation QueryEditorSerialization

		annotation TableWidgetSerialization

	annotation _TM_ExtProp_QueryDefinition = SELECT * FROM [Sales]

	annotation _TM_ExtProp_DbTableName = 905

	annotation IsQueryEditorUsed = False

	annotation QueryEditorSerialization

	annotation TableWidgetSerialization

	annotation DataMarketWebBaseUrl

	annotation DataMarketWebQueryUrl

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

