table 'Incident Finding'
	lineageTag: 3b15c03e-a70b-4a81-942e-486b4ddfe824

	column Findings
		dataType: string
		lineageTag: f5e8304f-4089-48db-b2a6-01b7bae757b2
		summarizeBy: none
		sourceColumn: Findings

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: f55c6d7d-a246-46dd-adb2-dc8283e96c43
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 35beb30d-57cc-43ba-bd14-e7b98f5fb50b
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FindingCategory
		dataType: string
		lineageTag: d9aaea0e-a6a8-4367-bb34-e937a7e2e6c6
		summarizeBy: none
		sourceColumn: FindingCategory

		annotation SummarizationSetBy = Automatic

	column 'ESPA Finding Area '
		dataType: string
		lineageTag: 7c1cfd72-5bae-4920-a207-8d4c1c146ca7
		summarizeBy: none
		sourceColumn: "ESPA Finding Area "

		annotation SummarizationSetBy = Automatic

	column 'Abnormal Finding Area'
		dataType: string
		lineageTag: e5b0bfa5-f29b-4445-bb5d-645c7c4b6efc
		summarizeBy: none
		sourceColumn: Abnormal Finding Area

		annotation SummarizationSetBy = Automatic

	column 'Non ESPA Finding Area'
		dataType: string
		lineageTag: 99441647-ef7c-47cf-bd81-55b4652e6345
		summarizeBy: none
		sourceColumn: Non ESPA Finding Area

		annotation SummarizationSetBy = Automatic

	column 'Alarm/ False Alarm'
		dataType: string
		lineageTag: e9e13759-c7a2-48f6-b1f9-9fcb4b31eccb
		summarizeBy: none
		sourceColumn: Alarm/ False Alarm

		annotation SummarizationSetBy = Automatic

	column 'Alarm Type'
		dataType: string
		lineageTag: 3fc3982b-efd1-4d86-a890-c93e68fbda13
		summarizeBy: none
		sourceColumn: Alarm Type

		annotation SummarizationSetBy = Automatic

	column Where
		dataType: string
		lineageTag: 486719ec-7f6e-4c70-824d-778896c07819
		summarizeBy: none
		sourceColumn: Where

		annotation SummarizationSetBy = Automatic

	column 'Photos(Good Finding)'
		dataType: string
		lineageTag: 9206756f-0daf-4801-8d6f-d2aaf16add62
		summarizeBy: none
		sourceColumn: Photos(Good Finding)

		annotation SummarizationSetBy = Automatic

	column 'Good Findings'
		dataType: string
		lineageTag: 1cd3e6bf-e35c-4fb1-8064-6d58e4ffdefc
		summarizeBy: none
		sourceColumn: Good Findings

		annotation SummarizationSetBy = Automatic

	column 'Abnormal Findings'
		dataType: string
		lineageTag: 28b7c99e-fa94-4c67-ae3d-37663bf1f7bc
		summarizeBy: none
		sourceColumn: Abnormal Findings

		annotation SummarizationSetBy = Automatic

	column 'Photos (Abnormal Findings)'
		dataType: string
		lineageTag: d4295c6e-5304-4468-b395-702aae038962
		summarizeBy: none
		sourceColumn: Photos (Abnormal Findings)

		annotation SummarizationSetBy = Automatic

	column Actions
		dataType: string
		lineageTag: 62adb9f9-ad24-4579-a741-92b8ec18ac3c
		summarizeBy: none
		sourceColumn: Actions

		annotation SummarizationSetBy = Automatic

	column 'Responsible By'
		dataType: string
		lineageTag: e2a8af3e-0511-4071-9a0c-0908e031acd1
		summarizeBy: none
		sourceColumn: Responsible By

		annotation SummarizationSetBy = Automatic

	column Complaint/Appreciation
		dataType: string
		lineageTag: 045b7249-233f-4edc-9084-56a100c3bfdd
		summarizeBy: none
		sourceColumn: Complaint/Appreciation

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 988ce10b-5711-433c-ada2-d845b0a8f224
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Associated files'
		dataType: string
		lineageTag: eb77b108-ad33-4d5c-81a2-1609e8a698a9
		summarizeBy: none
		sourceColumn: Associated files

		annotation SummarizationSetBy = Automatic

	column 'Color Tag'
		dataType: string
		lineageTag: 5ef2e3c7-dcd2-4c4b-9165-8640b2ad12dc
		summarizeBy: none
		sourceColumn: Color Tag

		annotation SummarizationSetBy = Automatic

	column 'Compliance Asset Id'
		dataType: string
		lineageTag: f4b78fcc-b88b-4a30-9e4f-32ba6e046262
		summarizeBy: none
		sourceColumn: Compliance Asset Id

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 78f6aaaf-79ee-422a-b538-170e8504e78c
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 00c92cf2-8618-4c74-b402-4669b59f5484
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Assigned to'
		dataType: string
		lineageTag: 118bfe46-fbea-4d82-b1db-d1585fe3a9dd
		summarizeBy: none
		sourceColumn: Assigned to

		annotation SummarizationSetBy = Automatic

	column 'Related issue'
		dataType: string
		lineageTag: c1e223f0-eb30-47ce-b268-df3d544687cc
		summarizeBy: none
		sourceColumn: Related issue

		annotation SummarizationSetBy = Automatic

	column CorA_Area
		dataType: string
		lineageTag: aa1c03f7-020e-40d4-8c24-ee8f01c30b48
		summarizeBy: none
		sourceColumn: CorA_Area

		annotation SummarizationSetBy = Automatic

	column 'Content Type'
		dataType: string
		lineageTag: a5f8dc3c-c3da-424f-a482-fd5262834d34
		summarizeBy: none
		sourceColumn: Content Type

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: dateTime
		formatString: General Date
		lineageTag: 4f4e7eec-ec7c-4822-8598-5ecd3488b184
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

	column 'Modified By'
		dataType: string
		lineageTag: 4b586aef-cf81-4a86-a8d8-1c97a55a28ab
		summarizeBy: none
		sourceColumn: Modified By

		annotation SummarizationSetBy = Automatic

	column Edit
		dataType: string
		lineageTag: 6f3a0aae-cead-4ac4-aa01-eec8a2af5cb8
		summarizeBy: none
		sourceColumn: Edit

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: d3aa259a-4d9b-4356-8cae-9a81d7a7614c
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Item Child Count'
		dataType: string
		lineageTag: e8a0cf96-36b2-402c-a198-a0ab09339954
		summarizeBy: none
		sourceColumn: Item Child Count

		annotation SummarizationSetBy = Automatic

	column 'Folder Child Count'
		dataType: string
		lineageTag: edb788e3-ea01-45c7-b9b2-1b373eb76220
		summarizeBy: none
		sourceColumn: Folder Child Count

		annotation SummarizationSetBy = Automatic

	column 'Label setting'
		dataType: string
		lineageTag: 9ba10702-0bbd-44de-8014-e0e274b4f2e9
		summarizeBy: none
		sourceColumn: Label setting

		annotation SummarizationSetBy = Automatic

	column 'Retention label'
		dataType: string
		lineageTag: 260f37a8-bd1b-4816-8327-07651b3803d7
		summarizeBy: none
		sourceColumn: Retention label

		annotation SummarizationSetBy = Automatic

	column 'Retention label Applied'
		dataType: string
		lineageTag: f04c742b-188b-45a7-b025-fd4f090364a5
		summarizeBy: none
		sourceColumn: Retention label Applied

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: string
		lineageTag: bdba5821-4bd5-42cb-b1d9-e99cfe84076a
		summarizeBy: none
		sourceColumn: Weekday

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: string
		lineageTag: a18bc534-c9ef-40dc-8e28-7fc69205ada3
		summarizeBy: none
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = Automatic

	column ESPAFindingArea_num
		dataType: int64
		formatString: 0
		lineageTag: 3c773e25-8a1d-4218-aad7-fbc05726c942
		summarizeBy: sum
		sourceColumn: ESPAFindingArea_num

		annotation SummarizationSetBy = Automatic

	partition 'Incident Finding' = m
		mode: import
		source =
				let
				    Source = Security_Q,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([FindingCategory] = "Incident Finding (ESPA)" or [FindingCategory] = "Incident Finding (Non-ESPA)")),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Filtered Rows", "ESPA Finding Area ", "ESPA Finding Area  - Copy"),
				    #"Extracted Text After Delimiter" = Table.TransformColumns(#"Duplicated Column", {{"ESPA Finding Area  - Copy", each Text.AfterDelimiter(_, "A"), type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Extracted Text After Delimiter",{{"ESPA Finding Area  - Copy", "ESPAFindingArea_num"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Findings", "Created", "Date", "FindingCategory", "ESPA Finding Area ", "ESPAFindingArea_num", "Abnormal Finding Area", "Non ESPA Finding Area", "Alarm/ False Alarm", "Alarm Type", "Where", "Photos(Good Finding)", "Good Findings", "Abnormal Findings", "Photos (Abnormal Findings)", "Actions", "Responsible By", "Complaint/Appreciation", "ID", "Associated files", "Color Tag", "Compliance Asset Id", "Priority", "Status", "Assigned to", "Related issue", "CorA_Area", "Content Type", "Modified", "Modified By", "Edit", "Type", "Item Child Count", "Folder Child Count", "Label setting", "Retention label", "Retention label Applied", "Weekday", "DayOfMonth"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Reordered Columns",{{"ESPAFindingArea_num", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

