table 'LEGO Security Training'
	lineageTag: 8bf9ce1a-c237-47e5-bfd3-8c893e25a7d9

	column Week
		dataType: string
		lineageTag: c9856763-3ee0-4c59-bfae-d54ed75bec77
		summarizeBy: none
		sourceColumn: Week
		sortByColumn: WeekNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Times
		dataType: int64
		formatString: 0
		lineageTag: ed178365-dd36-4d08-aca5-ee12fca125d1
		summarizeBy: none
		sourceColumn: Times

		annotation SummarizationSetBy = Automatic

	column Trainee
		dataType: string
		lineageTag: da89d787-a765-4f4c-ad9e-c4ee780219c5
		summarizeBy: none
		sourceColumn: Trainee

		annotation SummarizationSetBy = Automatic

	column Trainer
		dataType: string
		lineageTag: fb0fd632-1d87-4aed-ad49-6b23f7dc98f0
		summarizeBy: none
		sourceColumn: Trainer

		annotation SummarizationSetBy = Automatic

	column WeekNum
		dataType: int64
		formatString: 0
		lineageTag: a9408a55-50e1-4270-8138-fb848337dd4b
		summarizeBy: none
		sourceColumn: WeekNum

		annotation SummarizationSetBy = Automatic

	column WeekStartDate =
			
			VAR w = 'LEGO Security Training'[WeekNum]
			VAR y = YEAR( TODAY() )
			RETURN
			CALCULATE(
			    MIN( 'dDate'[Date] ),
			    'dDate'[WeekNum] = w,
			    YEAR( 'dDate'[Date] ) = y
			)
		formatString: Short Date
		lineageTag: b8fa62c5-32a3-4b99-992e-9f02dbbc9234
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'LEGO Security Training' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALCI/Shared%20Documents/General/03_BI/01_Project%20List/02.%20Project%20List/09.%20Security%20Digital%20Huddle/Security%20Huddle%20Update.xlsx"), null, true),
				    #"Security Training_Sheet" = Source{[Item="Security Training",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Security Training_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Week", type text}, {"Times", Int64.Type}, {"Trainee", type text}, {"Trainer", type text}}),
				    #"Inserted Text After Delimiter" = Table.AddColumn(#"Changed Type", "Text After Delimiter", each Text.AfterDelimiter([Week], "K"), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Text After Delimiter",{{"Text After Delimiter", "WeekNum"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"WeekNum", Int64.Type}}),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Changed Type1",1)
				in
				    #"Removed Bottom Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

