table 'Night Inspection'
	lineageTag: 606940e0-552d-43e0-9913-c4580ac285f2

	column Findings
		dataType: string
		lineageTag: a00944be-62af-4407-bd52-7b984325f8d7
		summarizeBy: none
		sourceColumn: Findings

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: fe1d80ce-e4b5-4bb6-93b7-603ab94ec1cd
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1af43e07-8032-4bc4-832b-2b42d88f8b77
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FindingCategory
		dataType: string
		lineageTag: bafead74-7c73-464b-8d8b-233de5f4c335
		summarizeBy: none
		sourceColumn: FindingCategory

		annotation SummarizationSetBy = Automatic

	column 'ESPA Finding Area '
		dataType: string
		lineageTag: 92ecabcf-4093-43e0-aa09-804b26b1d693
		summarizeBy: none
		sourceColumn: "ESPA Finding Area "

		annotation SummarizationSetBy = Automatic

	column 'Abnormal Finding Area'
		dataType: string
		lineageTag: 59a4a942-d616-4fbd-a06a-e5019caec3d4
		summarizeBy: none
		sourceColumn: Abnormal Finding Area

		annotation SummarizationSetBy = Automatic

	column 'Non ESPA Finding Area'
		dataType: string
		lineageTag: ade5bc2a-7de6-4bc6-afa3-ff28db986b9c
		summarizeBy: none
		sourceColumn: Non ESPA Finding Area

		annotation SummarizationSetBy = Automatic

	column 'Alarm/ False Alarm'
		dataType: string
		lineageTag: 3af6218b-a425-4227-9029-384a078b234c
		summarizeBy: none
		sourceColumn: Alarm/ False Alarm

		annotation SummarizationSetBy = Automatic

	column 'Alarm Type'
		dataType: string
		lineageTag: 1cfbb726-4d11-45e7-9b5d-4b2d8aa686e0
		summarizeBy: none
		sourceColumn: Alarm Type

		annotation SummarizationSetBy = Automatic

	column Where
		dataType: string
		lineageTag: 549da05d-837a-4969-a7e6-676e7028931a
		summarizeBy: none
		sourceColumn: Where

		annotation SummarizationSetBy = Automatic

	column 'Photos(Good Finding)'
		dataType: string
		lineageTag: 1cebefbc-da03-4a7e-9bc5-5a3700d5c6d1
		summarizeBy: none
		sourceColumn: Photos(Good Finding)

		annotation SummarizationSetBy = Automatic

	column 'Good Findings'
		dataType: string
		lineageTag: e22abdb5-6313-47a1-9a0d-cedbec367f12
		summarizeBy: none
		sourceColumn: Good Findings

		annotation SummarizationSetBy = Automatic

	column 'Abnormal Findings'
		dataType: string
		lineageTag: ce2cfde7-741d-412c-b208-7fda3de11444
		summarizeBy: none
		sourceColumn: Abnormal Findings

		annotation SummarizationSetBy = Automatic

	column 'Photos (Abnormal Findings)'
		dataType: string
		lineageTag: 7c13f950-1623-4de2-9e43-98ce8a998d55
		summarizeBy: none
		sourceColumn: Photos (Abnormal Findings)

		annotation SummarizationSetBy = Automatic

	column Actions
		dataType: string
		lineageTag: e7e1a225-31d3-4642-9ba3-360e2b3e7b68
		summarizeBy: none
		sourceColumn: Actions

		annotation SummarizationSetBy = Automatic

	column 'Responsible By'
		dataType: string
		lineageTag: 9cf68d02-f725-4297-94be-043e5b2ac9d6
		summarizeBy: none
		sourceColumn: Responsible By

		annotation SummarizationSetBy = Automatic

	column Complaint/Appreciation
		dataType: string
		lineageTag: 3c945317-0d5d-4b0f-9b10-c80abbab9a21
		summarizeBy: none
		sourceColumn: Complaint/Appreciation

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: c8a8d774-e229-4446-8853-3135d403a2ae
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Associated files'
		dataType: string
		lineageTag: 4945d946-56ad-48f0-83ca-8180eed2e6b4
		summarizeBy: none
		sourceColumn: Associated files

		annotation SummarizationSetBy = Automatic

	column 'Color Tag'
		dataType: string
		lineageTag: 30b5dcf0-45b8-4a85-8332-2befa26c7f6e
		summarizeBy: none
		sourceColumn: Color Tag

		annotation SummarizationSetBy = Automatic

	column 'Compliance Asset Id'
		dataType: string
		lineageTag: d3a969d7-1951-400b-8f7c-8b4c316a6897
		summarizeBy: none
		sourceColumn: Compliance Asset Id

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 5eab9353-aff4-4ac3-b9f9-38513b6646e4
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: f6ee5957-f75f-488e-8662-b66d9fc58f6e
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Assigned to'
		dataType: string
		lineageTag: a53b6b79-f378-472e-96d3-ae586f69bec6
		summarizeBy: none
		sourceColumn: Assigned to

		annotation SummarizationSetBy = Automatic

	column 'Related issue'
		dataType: string
		lineageTag: eb6a2b0f-86d3-453d-a551-676b332368eb
		summarizeBy: none
		sourceColumn: Related issue

		annotation SummarizationSetBy = Automatic

	column CorA_Area
		dataType: string
		lineageTag: 2d5aa599-1ecd-484e-a4d4-0c0de71430af
		summarizeBy: none
		sourceColumn: CorA_Area

		annotation SummarizationSetBy = Automatic

	column 'Content Type'
		dataType: string
		lineageTag: 6381c3c7-d538-495b-8a0c-9bcdd989b63a
		summarizeBy: none
		sourceColumn: Content Type

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: dateTime
		formatString: General Date
		lineageTag: 479462fa-7b3e-42b3-8c80-06f822142ffa
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

	column 'Modified By'
		dataType: string
		lineageTag: 1908ddac-4abf-4363-a152-9bbe2e846124
		summarizeBy: none
		sourceColumn: Modified By

		annotation SummarizationSetBy = Automatic

	column Edit
		dataType: string
		lineageTag: 449c5d09-1545-43f5-a984-bff9735aec99
		summarizeBy: none
		sourceColumn: Edit

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 7f2befd3-160d-43c8-9164-107300e2c4d0
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Item Child Count'
		dataType: string
		lineageTag: 9f14a244-8c66-42af-a4a9-1d7453ad6630
		summarizeBy: none
		sourceColumn: Item Child Count

		annotation SummarizationSetBy = Automatic

	column 'Folder Child Count'
		dataType: string
		lineageTag: 5186c2c6-f230-403e-9ff5-2ff07689b184
		summarizeBy: none
		sourceColumn: Folder Child Count

		annotation SummarizationSetBy = Automatic

	column 'Label setting'
		dataType: string
		lineageTag: 1d18903f-f998-4073-a270-3c685faab312
		summarizeBy: none
		sourceColumn: Label setting

		annotation SummarizationSetBy = Automatic

	column 'Retention label'
		dataType: string
		lineageTag: f57ed4f1-bfe3-46b7-8edc-2f03588cd126
		summarizeBy: none
		sourceColumn: Retention label

		annotation SummarizationSetBy = Automatic

	column 'Retention label Applied'
		dataType: string
		lineageTag: 4b92a397-f939-4949-bf8b-32e5c5f204dd
		summarizeBy: none
		sourceColumn: Retention label Applied

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: string
		lineageTag: f360fdf1-cbaa-4828-b5af-6ceb25b6ff62
		summarizeBy: none
		sourceColumn: Weekday

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: string
		lineageTag: a2983086-6350-405d-9740-388148dded2b
		summarizeBy: none
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = Automatic

	partition 'Night Inspection' = m
		mode: import
		source =
				let
				    Source = Security_Q,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([FindingCategory] = "Night Inspection"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

