table '2025 GLS PLAN'
	lineageTag: c6230a17-8b72-4201-9103-76fb3b0169ac

	column Month
		dataType: string
		lineageTag: 024d5031-f54b-412a-a4ec-219197261916
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'GLS #'
		dataType: string
		lineageTag: f2f0ac0d-c716-4d78-83bc-e6f8897f84ff
		summarizeBy: none
		sourceColumn: GLS #

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: string
		lineageTag: 61bac38c-792c-436f-9f0e-3a66278406ff
		summarizeBy: none
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column 'Cat.'
		dataType: string
		lineageTag: f360b777-ddcd-4856-b704-7e7506c67a41
		summarizeBy: none
		sourceColumn: Cat.

		annotation SummarizationSetBy = Automatic

	column 'GLS Area'
		dataType: string
		lineageTag: 1ed5aef2-0752-4dbb-97c8-cdb3e3c5d5c4
		summarizeBy: none
		sourceColumn: GLS Area

		annotation SummarizationSetBy = Automatic

	column Time
		dataType: string
		lineageTag: 907bace2-8995-4c94-b1b9-c1fda334ca6b
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

	column 'Look What'
		dataType: string
		lineageTag: 623919a7-a04e-47a7-920f-05eae9e73158
		summarizeBy: none
		sourceColumn: Look What

		annotation SummarizationSetBy = Automatic

	column Driver/Owner
		dataType: string
		lineageTag: 0c5824a9-b699-4d48-9826-87468e762868
		summarizeBy: none
		sourceColumn: Driver/Owner

		annotation SummarizationSetBy = Automatic

	column Participants(自愿填写）
		dataType: string
		lineageTag: 5e7dcb38-2f23-4ff4-b081-af38cc308037
		summarizeBy: none
		sourceColumn: Participants(自愿填写）

		annotation SummarizationSetBy = Automatic

	column Optional
		dataType: string
		lineageTag: 68b90bb0-7823-42e0-9fea-2be85ac9d20c
		summarizeBy: none
		sourceColumn: Optional

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 45782c03-a3e3-44e2-96c2-3b52e8aaf5cc
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column MonthNum =
			SWITCH(
			    TRUE(),
			    '2025 GLS PLAN'[Month]="Jan",1,
			    '2025 GLS PLAN'[Month]="Feb",2,
			    '2025 GLS PLAN'[Month]="Mar",3,
			    '2025 GLS PLAN'[Month]="Apr",4,
			    '2025 GLS PLAN'[Month]="May",5,
			    '2025 GLS PLAN'[Month]="Jun",6,
			    '2025 GLS PLAN'[Month]="Jul",7,
			    '2025 GLS PLAN'[Month]="Aug",8,
			    '2025 GLS PLAN'[Month]="Sep",9,
			    '2025 GLS PLAN'[Month]="Oct",10,
			    '2025 GLS PLAN'[Month]="Nov",11,
			    12)
		formatString: 0
		lineageTag: 607cf06e-b333-4a22-a237-603caf84f860
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a55ca877-cffd-42e6-9d0d-b65b5fb0c5b5
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition '2025 GLS PLAN' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/CHJiaxingSecurity/Shared%20Documents/00%20Digital%20Huddle/Digital%20Huddle%20(Excel%E7%89%88-%E8%AF%95%E8%BF%90%E8%A1%8C%EF%BC%89/02%20Security%20GLS%20Plan%20(2025).xlsx"), null, true),
				    #"2025 PLAN_Sheet" = Source{[Item="2025 PLAN",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"2025 PLAN_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{" 2025 Security GLS PLAN", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type any}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type any}, {"Column13", type text}, {"Column14", type any}}),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers1",{{"Month", type text}, {"GLS #", type text}, {"Week", type text}, {"Cat.", type text}, {"GLS Area", type any}, {"Time", type text}, {"Look What", type text}, {"Driver/#(lf)Owner", type text}, {"Participants#(lf)(自愿填写）", type text}, {"Optional", type text}, {"Status", type text}, {"Column12", type any}, {"GLS Area_1", type text}, {"Total#(lf)Times", Int64.Type}}),
				    #"Filled Down" = Table.FillDown(#"Changed Type1",{"Month"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Filled Down",{"Column12", "GLS Area_1", "Total#(lf)Times"}),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Removed Columns", "Text Before Delimiter", each Text.BeforeDelimiter([Time], ","), type text),
				    #"Added Prefix" = Table.TransformColumns(#"Inserted Text Before Delimiter", {{"Text Before Delimiter", each "2025 " & _, type text}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Prefix",{{"Text Before Delimiter", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type2",{{"Text Before Delimiter", "Date"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

