table 'Penetration Test'
	lineageTag: 56b491a8-142d-4b8f-a817-b89e0c3a04b5

	column Title
		dataType: string
		lineageTag: 4b8fd5db-8ebf-4814-a838-145b655e446b
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: c86efa02-7e81-4e0c-a0cf-668c5b133ccd
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 30072525-bcff-4eb0-8a77-8b5b2140422d
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column AccessType
		dataType: string
		lineageTag: 8c87eecd-2652-4810-94c4-5207572e515e
		summarizeBy: none
		sourceColumn: AccessType

		annotation SummarizationSetBy = Automatic

	column 'Penetration Area'
		dataType: string
		lineageTag: 33c2b7f8-6f30-4892-8791-01b608088a99
		summarizeBy: none
		sourceColumn: Penetration Area

		annotation SummarizationSetBy = Automatic

	column Penetration_Result
		dataType: string
		lineageTag: 7f91a1ab-ec87-44df-969f-d12e2d48d4cd
		summarizeBy: none
		sourceColumn: Penetration_Result

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 99fe0d9a-1d38-4cbe-9254-b7acc8cf3e0b
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Finished
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5dfc0356-92c8-4806-a965-4b08d67da892
		summarizeBy: none
		sourceColumn: Finished

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 33aebeac-7197-4986-b34c-433e96693089
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: dateTime
		formatString: General Date
		lineageTag: 933aba9c-5c25-468b-a329-d3c399c0a34b
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: 15cd9d57-3743-40c9-943b-3b06899306dd
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 087e179e-c06d-43a1-9765-e80429bef4af
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Weekname
		dataType: string
		lineageTag: e8ee88c0-c8aa-40ef-a282-5da329527487
		summarizeBy: none
		sourceColumn: Weekname

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: string
		lineageTag: 56c2df19-a03c-4446-92c2-4297581afe1b
		summarizeBy: none
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = Automatic

	column AccessUserType
		dataType: string
		lineageTag: 58904bec-ec10-414d-991d-6642b5941d3f
		summarizeBy: none
		sourceColumn: AccessUserType

		annotation SummarizationSetBy = Automatic

	partition 'Penetration Test' = m
		mode: import
		source =
				let
				    Source = Security_D,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Category] = "Penetration Test")),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"AccessCategory", "Content Type", "Created By", "Modified By", "Attachments", "Item Child Count", "Folder Child Count", "Label setting", "Retention label", "Retention label Applied", "Color Tag", "Compliance Asset Id"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

