table 'Phsical Training (Non-ESPA)'
	lineageTag: eb960b29-9463-4026-9ef1-f7284c78a2d3

	column 训练场次
		dataType: int64
		formatString: 0
		lineageTag: 9bd08841-f6dd-4b0b-869d-05ef5185d0f2
		summarizeBy: sum
		sourceColumn: 训练场次

		annotation SummarizationSetBy = Automatic

	column 训练时间
		dataType: dateTime
		formatString: Short Date
		lineageTag: 3f244e9c-03fc-4359-aef9-4b3bfbcaaabe
		summarizeBy: none
		sourceColumn: 训练时间

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 训练地点
		dataType: string
		lineageTag: d28643fa-e091-4ce6-a66e-85a5c6d05597
		summarizeBy: none
		sourceColumn: 训练地点

		annotation SummarizationSetBy = Automatic

	column 教练
		dataType: string
		lineageTag: d94ed993-06ab-4b47-aab6-2802046b5c23
		summarizeBy: none
		sourceColumn: 教练

		annotation SummarizationSetBy = Automatic

	column 参加人数
		dataType: string
		lineageTag: 880e8c09-f1a6-4abc-98e7-1438546acd4e
		summarizeBy: none
		sourceColumn: 参加人数

		annotation SummarizationSetBy = Automatic

	column 体能通过率
		dataType: double
		formatString: 0%;-0%;0%
		lineageTag: cee6ea40-2287-48d8-a5a1-07aa8460c99d
		summarizeBy: sum
		sourceColumn: 体能通过率

		annotation SummarizationSetBy = Automatic

	partition 'Phsical Training (Non-ESPA)' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALCI/Shared%20Documents/General/03_BI/01_Project%20List/02.%20Project%20List/09.%20Security%20Digital%20Huddle/%E5%9F%B9%E8%AE%AD&%E4%BD%93%E8%83%BD%E8%AE%AD%E7%BB%83(Non-ESPA).xlsx"), null, true),
				    Table2_Table = Source{[Item="PhsicalTrainingNonESPA",Kind="Table"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(Table2_Table, each ([训练场次] <> null)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"训练场次", Int64.Type}, {"训练时间", type date}, {"体能通过率", Percentage.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

