table 'S&M mulfunction'
	lineageTag: d3de9365-5674-40c5-8bd5-93f6623911e6

	column Department
		dataType: string
		lineageTag: f0ad3c2a-c16f-44a3-9048-61f454516d21
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 898203ec-1f92-4c41-962a-bf4b740c96fd
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 已完成
		dataType: int64
		lineageTag: 2595c339-af67-435e-915c-713cd9cb9d7d
		summarizeBy: sum
		sourceColumn: 已完成

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 暂不维修
		dataType: int64
		lineageTag: 7c28db1c-0f0c-48c4-a5ac-d3f316da7eef
		summarizeBy: sum
		sourceColumn: 暂不维修

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 维修进行中
		dataType: int64
		lineageTag: d8ce5f31-13e8-4649-b23c-aede45ebcb1f
		summarizeBy: sum
		sourceColumn: 维修进行中

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 重大维修
		dataType: int64
		lineageTag: 11f97b11-a59f-4542-8cdb-f720250d8099
		summarizeBy: sum
		sourceColumn: 重大维修

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MonthNumber = ```
			
			  SWITCH(
			    [Month],
			    "一月",   1,
			    "二月",   2,
			    "三月",   3,
			    "四月",   4,
			    "五月",   5,
			    "六月",   6,
			    "七月",   7,
			    "八月",   8,
			    "九月",   9,
			    "十月",  10,
			    "十一月",11,
			    "十二月",12,
			    BLANK()
			  )
			```
		formatString: 0
		lineageTag: 592f3e44-f3e6-4a15-a83f-357802e74bb6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column MonthStartDate = ```
			
			  FORMAT(DATE( YEAR(TODAY()), [MonthNumber], 1 ),"mmm","en-US")
			```
		lineageTag: fbb35347-1b99-4e8d-954a-23897a329451
		summarizeBy: none
		sortByColumn: MonthNumber

		changedProperty = DataType

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'S&M mulfunction' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/:x:/r/sites/JIALCI/Shared%20Documents/General/03_BI/01_Project%20List/02.%20Project%20List/09.%20Security%20Digital%20Huddle/S%26M%20mulfunction.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Department", type text}, {"Month", type text}, {"已完成", Int64.Type}, {"暂不维修", Int64.Type}, {"维修进行中", Int64.Type}, {"重大维修", Int64.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",null,0,Replacer.ReplaceValue,{"已完成", "暂不维修", "维修进行中", "重大维修"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

