table Security_D
	lineageTag: 59d485f7-f10e-4897-80d4-eb0f964d325a

	column Title
		dataType: string
		lineageTag: 04a2be3a-59f6-47da-ad8f-e1c3e841dcef
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: aba04434-bdf8-4eb9-ba11-d879a5c0a730
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: df6d812f-2e14-4cd7-9c88-36667d2f7d1b
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column AccessType
		dataType: string
		lineageTag: c3018ba8-51f7-407d-8d02-1879ecba565b
		summarizeBy: none
		sourceColumn: AccessType

		annotation SummarizationSetBy = Automatic

	column 'Penetration Area'
		dataType: string
		lineageTag: 66c7f79d-7b59-4cea-a5ff-fad568d4317d
		summarizeBy: none
		sourceColumn: Penetration Area

		annotation SummarizationSetBy = Automatic

	column Penetration_Result
		dataType: string
		lineageTag: 456ffb98-825e-402d-ab0b-858ea658c9c7
		summarizeBy: none
		sourceColumn: Penetration_Result

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4814a71f-746b-40aa-8c8f-78cb9086a462
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Finished
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5b9f4d39-dcef-48f6-b8fb-e81710735906
		summarizeBy: none
		sourceColumn: Finished

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 7726cd16-7a5b-4b0b-885e-0985aad3e425
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: dateTime
		formatString: General Date
		lineageTag: 48b83e59-704c-4c2f-8187-7f493ae8732e
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: f695df7f-3988-4f78-b484-ab58a253dad3
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 11839ca0-7ff8-4cc0-8a8c-5ecf67e9ad51
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Color Tag'
		dataType: string
		lineageTag: 8591d0c6-bd84-4416-9cce-1edba726a21c
		summarizeBy: none
		sourceColumn: Color Tag

		annotation SummarizationSetBy = Automatic

	column 'Compliance Asset Id'
		dataType: string
		lineageTag: 59a4de57-c47e-45a9-b768-98b4c633e4de
		summarizeBy: none
		sourceColumn: Compliance Asset Id

		annotation SummarizationSetBy = Automatic

	column 'Content Type'
		dataType: string
		lineageTag: dde4114b-3efd-4d82-a4ec-7dcc4da5de7a
		summarizeBy: none
		sourceColumn: Content Type

		annotation SummarizationSetBy = Automatic

	column 'Created By'
		dataType: string
		lineageTag: dcb7f363-f3e1-4bd1-9b1f-79672544a2ff
		summarizeBy: none
		sourceColumn: Created By

		annotation SummarizationSetBy = Automatic

	column 'Modified By'
		dataType: string
		lineageTag: 2f5d5e0b-1085-4a6a-b468-4545734cb466
		summarizeBy: none
		sourceColumn: Modified By

		annotation SummarizationSetBy = Automatic

	column Attachments
		dataType: string
		lineageTag: 451558a9-42d1-411e-82c6-0f95274696f9
		summarizeBy: none
		sourceColumn: Attachments

		annotation SummarizationSetBy = Automatic

	column 'Item Child Count'
		dataType: string
		lineageTag: dd09fad2-0665-45d7-8e6d-ac10afeb5d8b
		summarizeBy: none
		sourceColumn: Item Child Count

		annotation SummarizationSetBy = Automatic

	column 'Folder Child Count'
		dataType: string
		lineageTag: a6983555-c505-44f6-9559-bbe8491126d2
		summarizeBy: none
		sourceColumn: Folder Child Count

		annotation SummarizationSetBy = Automatic

	column 'Label setting'
		dataType: string
		lineageTag: f06d33ac-578e-400d-9372-1620829e7f28
		summarizeBy: none
		sourceColumn: Label setting

		annotation SummarizationSetBy = Automatic

	column 'Retention label'
		dataType: string
		lineageTag: 9406cd7a-6c0d-486e-88b8-8633f6795837
		summarizeBy: none
		sourceColumn: Retention label

		annotation SummarizationSetBy = Automatic

	column 'Retention label Applied'
		dataType: string
		lineageTag: 194d2b3c-33ae-44fe-bd5b-e4807c1930d4
		summarizeBy: none
		sourceColumn: Retention label Applied

		annotation SummarizationSetBy = Automatic

	column Weekname
		dataType: string
		lineageTag: e6fb0baf-6039-48ab-83ee-57129efb8462
		summarizeBy: none
		sourceColumn: Weekname

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: string
		lineageTag: d1aed819-d27a-44b2-8f6d-a5c53b4c034c
		summarizeBy: none
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = Automatic

	column AccessUserType
		dataType: string
		lineageTag: cfefddad-6bab-4b57-b93d-4527567dcc0b
		summarizeBy: none
		sourceColumn: AccessUserType

		annotation SummarizationSetBy = Automatic

	column AccessCategory
		dataType: string
		lineageTag: d0109847-54f7-4e24-8753-a68da6d67559
		summarizeBy: none
		sourceColumn: AccessCategory

		annotation SummarizationSetBy = Automatic

	partition Security_D = m
		mode: import
		source =
				let
				    Source = SharePoint.Tables("https://legogroup.sharepoint.com/sites/JIALCI/", [Implementation="2.0", ViewMode="All"]),
				    #"ca653af2-3f21-4105-9ef3-c4f24d09266e" = Source{[Id="ca653af2-3f21-4105-9ef3-c4f24d09266e"]}[Items],
				    #"Removed Columns" = Table.RemoveColumns(#"ca653af2-3f21-4105-9ef3-c4f24d09266e",{"Version", "Edit", "Label applied by", "Item is a Record", "App Created By", "App Modified By"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"Date", type date}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Weekname", each Date.ToText([Date], "ddd", "en-US")),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "DayOfMonth", each Date.Day([Date]))
				in
				    #"Added Custom1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

