table 'Electricity Area'
	lineageTag: 5db6cb85-7e5c-4933-9a52-55a09b5f77e7

	column Cabinet
		dataType: string
		lineageTag: 35ab68d4-b57c-45e1-ba3e-39fdc8e8961a
		summarizeBy: none
		sourceColumn: Cabinet

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SN
		dataType: string
		lineageTag: dc0caed6-f4cd-4fd4-b3fb-142d4f038cd3
		summarizeBy: none
		sourceColumn: SN

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Meter
		dataType: string
		lineageTag: ad4b8ad4-2dab-4c65-844f-21ab442283e0
		summarizeBy: none
		sourceColumn: Meter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Swithboard
		dataType: string
		lineageTag: 0a4fc99a-2a69-43eb-a92f-304bd09ca853
		summarizeBy: none
		sourceColumn: Swithboard

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 按照属性分
		dataType: string
		isHidden
		lineageTag: db244b76-41e3-45b5-b7b7-611194601352
		summarizeBy: none
		sourceColumn: 按照属性分

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 按照区域分
		dataType: string
		lineageTag: 361138e6-4e7d-41d3-83db-1ae791704e89
		summarizeBy: none
		sourceColumn: 按照区域分

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: a04d344d-7711-4b39-9d1e-5cf7e25b97c1
		summarizeBy: none
		sourceColumn: Category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 用途
		dataType: string
		lineageTag: 3077dbaa-c963-4f9a-93ac-c2945a74e7ae
		summarizeBy: none
		sourceColumn: 用途

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 备注
		dataType: string
		isHidden
		lineageTag: 6fd6acb2-87c4-4ed8-8448-faf2236a17a9
		summarizeBy: none
		sourceColumn: 备注

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 区域分类
		dataType: string
		isHidden
		lineageTag: 79f4c5c3-e72a-4414-aae9-801c4f7c053f
		summarizeBy: none
		sourceColumn: 区域分类

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 使用区域
		dataType: string
		lineageTag: 6ec5e6f4-bb57-4aa3-b5e3-e863ac88f82f
		summarizeBy: none
		sourceColumn: 使用区域

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 功能分类
		dataType: string
		isHidden
		lineageTag: fa69932e-b6f8-4538-8277-80a49d938cb3
		summarizeBy: none
		sourceColumn: 功能分类

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Electricity
		dataType: string
		lineageTag: a547f995-b031-4b6b-8b22-031f4150b1ef
		summarizeBy: none
		sourceColumn: Electricity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Category4
		dataType: string
		lineageTag: b5606af6-ec15-4c44-bccb-141366f1db6c
		summarizeBy: none
		sourceColumn: Category4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Electricity Area' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALCI/Shared%20Documents/General/03_BI/01_Project%20List/02.%20Project%20List/03.%20Energy%20Consumption/Energy%20BI%20-%20electricity%20number.xlsx"), null, true),
				    #"400v_Sheet" = Source{[Item="400v",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(#"400v_Sheet",1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers",{"Column15", "Column16", "Column17", "Column18", "Column19", "Column20"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each ([SN] <> null) and ([Swithboard] <> null)),
				    #"Trimmed Text" = Table.TransformColumns(#"Filtered Rows",{{"使用区域", Text.Trim, type text}})
				in
				    #"Trimmed Text"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

