table LFAC_EC冷机10kv
	isHidden
	lineageTag: f36e8ddd-2e58-4717-9b66-128319871324

	column Cabinet
		dataType: string
		isHidden
		lineageTag: f598344f-2a92-40bb-8476-7ec428ff0e30
		summarizeBy: none
		sourceColumn: Cabinet

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 3e93f1a8-81a0-4765-9d95-4a68deeda5fb
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Value
		dataType: double
		isHidden
		lineageTag: e7291859-a6c2-472e-9a3f-4c9467908fea
		summarizeBy: sum
		sourceColumn: Value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 使用区域
		dataType: string
		isHidden
		lineageTag: 73e7c735-b62e-4fad-807e-3306505fb06b
		summarizeBy: none
		sourceColumn: 使用区域

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 功能分类
		dataType: string
		isHidden
		lineageTag: 8e19f9a2-6c3b-40c2-830c-9913a9ba2690
		summarizeBy: none
		sourceColumn: 功能分类

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SN
		dataType: string
		lineageTag: c50353b0-4e19-4718-871c-fc086747e872
		summarizeBy: none
		sourceColumn: SN

		annotation SummarizationSetBy = Automatic

	partition LFAC_EC冷机10kv = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALFACTECH/Shared%20Documents/18%20%E8%83%BD%E6%BA%90%E4%BF%A1%E6%81%AF%E7%AE%A1%E7%90%86/01%20Energy%20Data%20%E8%83%BD%E6%BA%90%E6%95%B0%E6%8D%AE/%E8%83%BD%E6%BA%90%E4%B8%AD%E5%BF%83%E6%95%B0%E6%8D%AE%E8%AE%B0%E5%BD%95%E8%A1%A8%202025.xlsx"), null, true),
				    其他_Sheet = Source{[Item="其他",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(其他_Sheet,1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Filtered Rows2" = Table.SelectRows(#"Promoted Headers", each ([Cabinet] <> null)),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Filtered Rows2", {"Cabinet", "能源种类", "Unit", "备注"}, "Date", "Value"),
				    #"Filtered Rows" = Table.SelectRows(#"Unpivoted Other Columns", each ([Date] <> "Annual" and [Date] <> "APR" and [Date] <> "AUG" and [Date] <> "DEC" and [Date] <> "FEB" and [Date] <> "JAN" and [Date] <> "JUL" and [Date] <> "JUN" and [Date] <> "MAR" and [Date] <> "MAY" and [Date] <> "NOV" and [Date] <> "OCT" and [Date] <> "SEP")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Date", type date}, {"Value", type number}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"Date"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Removed Errors", each ([Cabinet] = "10kV冰机总用电")),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows1","10kV冰机总用电","310AT23",Replacer.ReplaceText,{"Cabinet"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Replaced Value",{"能源种类", "Unit", "备注"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "使用区域", each "CN0303"),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "功能分类", each "EC 冷机"),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "SN", each 508)
				in
				    #"Added Custom2"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

