table LFAC_Electricity400v
	lineageTag: 432313b8-0fcd-48a3-a54c-b7da6f0b4bb5

	column Cabinet
		dataType: string
		lineageTag: b82f3c18-58d6-4ede-bfc3-f15035fb362b
		summarizeBy: none
		sourceColumn: Cabinet

		annotation SummarizationSetBy = Automatic

	column SN
		dataType: string
		lineageTag: 846585ac-f0b0-4cfe-abe3-5ee07fb6271f
		summarizeBy: none
		sourceColumn: SN

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: d132b89c-b1c8-42fe-8078-4ae9f6de773f
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column Function
		dataType: string
		lineageTag: e2117324-56e5-439a-8d3a-3e81c6f96dbf
		summarizeBy: none
		sourceColumn: Function

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: m/d/yyyy
		lineageTag: 2faac42e-355e-4f7d-a393-14f2b760d12b
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 4b38cd39-5394-449d-9df9-fb76542c98c3
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition LFAC_Electricity400v = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALFACTECH/Shared%20Documents/18%20%E8%83%BD%E6%BA%90%E4%BF%A1%E6%81%AF%E7%AE%A1%E7%90%86/01%20Energy%20Data%20%E8%83%BD%E6%BA%90%E6%95%B0%E6%8D%AE/%E8%83%BD%E6%BA%90%E4%B8%AD%E5%BF%83%E6%95%B0%E6%8D%AE%E8%AE%B0%E5%BD%95%E8%A1%A8%202025.xlsx"), null, true),
				    #"400V 电表_Sheet" = Source{[Item="400V 电表",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(#"400V 电表_Sheet",1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Filtered Rows1" = Table.SelectRows(#"Promoted Headers", each ([SN] <> null)),
				    #"Filled Down" = Table.FillDown(#"Filtered Rows1",{"Cabinet"}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Filled Down", {"功能分类", "使用区域", "SN", "Cabinet"}, "Date", "Value"),
				    #"Filtered Rows" = Table.SelectRows(#"Unpivoted Other Columns", each ([Date] <> "Annual" and [Date] <> "APR" and [Date] <> "AUG" and [Date] <> "DEC" and [Date] <> "FEB" and [Date] <> "JAN" and [Date] <> "JUL" and [Date] <> "JUN" and [Date] <> "MAR" and [Date] <> "MAY" and [Date] <> "NOV" and [Date] <> "OCT" and [Date] <> "SEP")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Date", type date}, {"Value", Int64.Type}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type", {{"Value", 0}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Errors",{{"使用区域", "Area"}, {"功能分类", "Function"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

