table LFAC_Aircompressor
	lineageTag: 71dd8e40-fe49-409f-9e02-dbbe7c0ec0e4

	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 4b9ba26c-6941-4c7a-aa12-12f5d8bb5a5e
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Location
		dataType: string
		lineageTag: 41203611-7281-4edf-b0a1-661c1d8d0c02
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 90ecdc02-c81d-4a35-94fb-23905e339b7d
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Week
		dataType: string
		lineageTag: 50e00bcd-6d61-403c-9009-fadba8c90da6
		summarizeBy: none
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column 分表累计
		dataType: double
		lineageTag: 028100a5-2d83-4f12-9441-8a0f2ad9d529
		summarizeBy: sum
		sourceColumn: 分表累计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 气电比
		dataType: double
		lineageTag: 2dea3343-30a1-47a3-983a-895d2c121380
		summarizeBy: sum
		sourceColumn: 气电比

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 输入比功率
		dataType: double
		lineageTag: 4e94c2da-8ab1-4cb0-aa21-1f8e2728bc48
		summarizeBy: sum
		sourceColumn: 输入比功率

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 目标值
		dataType: string
		lineageTag: 9ec18236-852c-4867-9aa8-8eafe830a168
		summarizeBy: none
		sourceColumn: 目标值

		annotation SummarizationSetBy = Automatic

	column 负载率
		dataType: string
		lineageTag: 2853a650-7d27-40db-be8e-9da006153165
		summarizeBy: none
		sourceColumn: 负载率

		annotation SummarizationSetBy = Automatic

	partition LFAC_Aircompressor = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALFACTECH/Shared%20Documents/18%20%E8%83%BD%E6%BA%90%E4%BF%A1%E6%81%AF%E7%AE%A1%E7%90%86/01%20Energy%20Data%20%E8%83%BD%E6%BA%90%E6%95%B0%E6%8D%AE/%E8%83%BD%E6%BA%90%E4%B8%AD%E5%BF%83%E6%95%B0%E6%8D%AE%E8%AE%B0%E5%BD%95%E8%A1%A8%202025.xlsx"), null, true),
				    #"Air compressor_Sheet" = Source{[Item="Air compressor",Kind="Sheet"]}[Data],
				    #"Removed Top Rows1" = Table.Skip(#"Air compressor_Sheet",1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows1", [PromoteAllScalars=true]),
				    #"Removed Top Rows" = Table.Skip(#"Promoted Headers",28),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Removed Top Rows",59),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Bottom Rows",{{"                     计量#(lf)        日期", "Week"}, {"Column2", "Usages"}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Renamed Columns", {{"Week", null}}),
				    #"Filled Down" = Table.FillDown(#"Replaced Errors",{"Week", "分表累计", "气电比", "输入比功率", "目标值"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Filled Down",{"Column20", "CN101_1", "CN102_2", "CN103_3", "CN104_4", "CN105_5", "CN106_6", "CN202_7", "CN301_8", "CN302_9", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each ([Usages] = "实际用量") and ([CN303总表] <> null and [CN303总表] <> "")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"气电比", type number}, {"输入比功率", type number}, {"分表累计", type number}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"气电比"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Errors", "Date", each Date.StartOfWeek(Date.AddDays(#date(2025, 1, 1), ([Week] - 1) * 7), Day.Sunday)),
				    #"Unpivoted Only Selected Columns" = Table.Unpivot(#"Added Custom", {"CN101", "CN102", "CN103", "CN104", "CN105", "CN106", "CN202", "CN301", "CN302","CN303总表","CN205","CN304总表（M3供全厂）"}, "Location", "Value"),
				    #"Removed Columns1" = Table.RemoveColumns(#"Unpivoted Only Selected Columns",{"Usages"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns1",{{"Date", type date}, {"Value", type number}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

