table LFAC_Gas
	lineageTag: b494ba6a-092c-4f62-9508-0d86f205ea73

	column Cabinet
		dataType: string
		lineageTag: d09b0754-423d-4e0f-b75f-a2ad8d1815d3
		summarizeBy: none
		sourceColumn: Cabinet

		annotation SummarizationSetBy = Automatic

	column 能源种类
		dataType: string
		lineageTag: 2782e40c-e45e-4c7d-83b8-ef3a8825ba2a
		summarizeBy: none
		sourceColumn: 能源种类

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: 8848d18f-320c-4198-951b-261ebde1bc07
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column 备注
		dataType: string
		lineageTag: b4ba2021-b93a-44d3-8282-3f3cab7ed619
		summarizeBy: none
		sourceColumn: 备注

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 11f94a53-13f3-4cc8-afb4-c7ae880f434d
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Value
		dataType: double
		lineageTag: 5049b955-b36c-45cd-b734-ce55adba91f7
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition LFAC_Gas = m
		mode: import
		source =
				let
				    Source = LFAC_Others,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([能源种类] = "Gas")),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Filtered Rows", {"Date"})
				in
				    #"Removed Errors"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

