table LFAC_Aircompressor_ElectricityUsage
	lineageTag: b23487bb-e5b0-4471-8696-a29029d92c17

	column AirCompressor_PowerUsage
		dataType: double
		lineageTag: 3cb866b3-af49-42a5-8c97-210e2037dd4f
		summarizeBy: sum
		sourceColumn: AirCompressor_PowerUsage

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		isHidden
		formatString: m/d/yyyy
		lineageTag: c4b1bfd0-fce8-4006-ac23-f835faaa1d44
		summarizeBy: none
		sourceColumn: Date

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition LFAC_Aircompressor_ElectricityUsage = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALFACTECH/Shared%20Documents/18%20%E8%83%BD%E6%BA%90%E4%BF%A1%E6%81%AF%E7%AE%A1%E7%90%86/01%20Energy%20Data%20%E8%83%BD%E6%BA%90%E6%95%B0%E6%8D%AE/%E8%83%BD%E6%BA%90%E4%B8%AD%E5%BF%83%E6%95%B0%E6%8D%AE%E8%AE%B0%E5%BD%95%E8%A1%A8%202025.xlsx"), null, true),
				    Electricity_Sheet = Source{[Item="Electricity",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(Electricity_Sheet,1),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Top Rows",{"Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54"}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Columns", [PromoteAllScalars=true]),
				    #"Grouped Rows" = Table.Group(#"Promoted Headers", {"日期"}, {{"Count", each _}}, 0, (x,y)=> Number.From( y[日期]= null    ) ),
				    #"Added Custom" = Table.AddColumn(#"Grouped Rows", "Type", each [Count]{0}[1]),
				    #"Filtered Rows" = Table.SelectRows(#"Added Custom", each ([Type] = "Air compressor electricity consumption(kwh)空压耗电（所有空压）")),
				    Count = #"Filtered Rows"{0}[Count],
				    #"Removed Top Rows1" = Table.Skip(Count,1),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Top Rows1", {"日期"}, "Day", "AirCompressor_PowerUsage"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Unpivoted Other Columns",{{"日期", type date}, {"Day", Int64.Type}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type", "Date", each Date.AddDays([日期],[Day]-1)),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom1",{"日期", "Day"})
				in
				    #"Removed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

