table LFAC_Water
	lineageTag: 7b9a052f-17e7-4031-9272-5519e5a1b0c6

	column Cabinet
		dataType: string
		lineageTag: 5bb77673-1822-4fab-a63c-fd03a2f478c2
		summarizeBy: none
		sourceColumn: Cabinet

		annotation SummarizationSetBy = Automatic

	column 能源种类
		dataType: string
		lineageTag: eb8cd77a-c96f-4a01-a34d-5eb06b699f64
		summarizeBy: none
		sourceColumn: 能源种类

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: f50c2ee6-ef9b-48b1-b471-e6e033767800
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column 备注
		dataType: string
		lineageTag: 8dd6bad4-3237-41a2-94f9-1e26b8bfb10a
		summarizeBy: none
		sourceColumn: 备注

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0c13a290-d4b3-42dc-a582-e55e5e8aed8b
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Value
		dataType: double
		lineageTag: 77fc2d99-13ea-4988-9efb-f69bb08ce766
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition LFAC_Water = m
		mode: import
		source =
				let
				    Source = LFAC_Others,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([能源种类] = "City water")),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Filtered Rows", {"Date"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Errors","工厂总用水","工厂总用水Level 1",Replacer.ReplaceValue,{"Cabinet"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value","UTS总用水","UTS 总用水Level 3",Replacer.ReplaceValue,{"Cabinet"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value2","生活用水","生活用水 Level 2",Replacer.ReplaceValue,{"Cabinet"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value1","南北厨房用水","南北厨房用水 Level 3",Replacer.ReplaceValue,{"Cabinet"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","工艺绿化用水总","工艺绿化用水 Level 2",Replacer.ReplaceValue,{"Cabinet"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value5","生活用水总","生活用水（不包括UTS）Level 3",Replacer.ReplaceText,{"Cabinet"})
				in
				    #"Replaced Value3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

