table LFAC_HeatingCooling
	lineageTag: e373536e-fa94-4814-89c0-ff4e17f53c47

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3060c342-3d51-40c4-82f2-86464bc3a2db
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: f0ccab3c-c875-484e-9870-a55083c6ae74
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: a584d871-911f-442c-8b3f-f11ed635cf69
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Type
		dataType: string
		lineageTag: 376ed494-2a8e-4d11-86d0-9a42dd5e4e4a
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	partition LFAC_HeatingCooling = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALFACTECH/Shared%20Documents/18%20%E8%83%BD%E6%BA%90%E4%BF%A1%E6%81%AF%E7%AE%A1%E7%90%86/01%20Energy%20Data%20%E8%83%BD%E6%BA%90%E6%95%B0%E6%8D%AE/%E8%83%BD%E6%BA%90%E4%B8%AD%E5%BF%83%E6%95%B0%E6%8D%AE%E8%AE%B0%E5%BD%95%E8%A1%A8%202025.xlsx"), null, true),
				    #"冷量&热量input(60)_Sheet" = Source{[Item="冷量&热量input(60)",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(#"冷量&热量input(60)_Sheet",1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers",{"Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column4"}),
				    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Removed Columns", {{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}, "en-US"),{"Column1", "Column2", "Column3"},Combiner.CombineTextByDelimiter("/", QuoteStyle.None),"Date"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Merged Columns",{{"Date", type datetime}, {"冰机出水温度", type number}, {"出水冷表MWh#(lf)空压", type number}, {"出水冷表MWh#(lf)工艺水", type number}, {"出水冷表MWh#(lf)数据机房", type number}, {"出水冷表MWh#(lf)高架仓", type number}, {"出水冷表MWh#(lf)包装", type number}, {"出水冷表MWh#(lf)注塑", type number}, {"热水压力", type any}, {"分水器温度/给水温度", type number}, {"集水器温度/进水温度", type number}, {"出水热表MWh#(lf)包装", type number}, {"出水热表MWh#(lf)高架仓", type number}, {"出水热表MWh#(lf)注塑", type number}, {"PAC SMP#(lf)MWh", type number}, {"Processing#(lf)MWh", type number}, {"五号冰机热表MWh", type number}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type1", {"Date"}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Errors", {"Date"}, "Name", "Value"),
				    #"Merged Queries" = Table.NestedJoin(#"Unpivoted Other Columns", {"Name"}, dim_heatingcooling_type, {"Name"}, "dim_heatingcooling_type", JoinKind.LeftOuter),
				    #"Expanded dim_heatingcooling_type" = Table.ExpandTableColumn(#"Merged Queries", "dim_heatingcooling_type", {"Type"}, {"Type"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded dim_heatingcooling_type",{{"Value", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

