table 2026Identify
	lineageTag: 8256fcb1-7920-467b-a313-af41abbea5f0

	measure Identify2026 = ```
			
			var curDept = SELECTEDVALUE('2026Identify'[Dept],"JIA")
			var pre = "2026 Productivity Identified- " 
			RETURN
			    pre & curDept & " MDKK"
			```
		lineageTag: 52096b9b-0cc7-4108-b724-cff91f5ed25e

	column Dept
		dataType: string
		lineageTag: d7ec3e68-4ba5-4b05-9c26-3a4526a6cf5f
		summarizeBy: none
		sourceColumn: Dept

		annotation SummarizationSetBy = Automatic

	column Target
		dataType: double
		lineageTag: f954cc26-43f4-4fdc-92fc-e17db478a807
		summarizeBy: none
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Identify
		dataType: double
		lineageTag: 8fa990ac-7527-4d0b-9efb-5f7b48eac640
		summarizeBy: none
		sourceColumn: Identify

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IL 0-2'
		dataType: double
		lineageTag: 9bb98d19-6dc2-4771-bd08-23e770577ec8
		summarizeBy: none
		sourceColumn: IL 0-2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IL 3-5'
		dataType: double
		lineageTag: 08dc4d86-5d3c-47c8-a1f5-7e246924eebf
		summarizeBy: none
		sourceColumn: IL 3-5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GAP
		dataType: double
		lineageTag: 4233add1-2452-4b9a-9bc7-bbff4296b5b6
		summarizeBy: none
		sourceColumn: GAP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 2026Identify = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALCI/Shared%20Documents/General/03_BI/2026%20Identify.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Dept", type text}, {"Target", type number}, {"Identify", type number}, {"IL 0-2", type number}, {"IL 3-5", type number}, {"GAP", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

