table 2025Tooltip
	lineageTag: 2dceeb23-4a77-4acf-ae88-b47a251fc5f9

	column Area
		dataType: string
		lineageTag: 2cbc7a75-844f-430e-8c26-c314cd1550e2
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column 'Fin Target'
		dataType: int64
		formatString: 0
		lineageTag: a1c7d4d6-0584-42b7-a97d-d9b634d123f6
		summarizeBy: sum
		sourceColumn: Fin Target

		annotation SummarizationSetBy = Automatic

	column 'In Year Benefit'
		dataType: double
		formatString: 0.0
		lineageTag: 756fa819-9be8-44f9-aa7e-c23021dd0ec9
		summarizeBy: sum
		sourceColumn: In Year Benefit

		annotation SummarizationSetBy = Automatic

	column Gap
		dataType: double
		formatString: 0.0
		lineageTag: 4afcc190-7d3c-4832-8c2c-70ffd98c79e5
		summarizeBy: sum
		sourceColumn: Gap

		annotation SummarizationSetBy = Automatic

	column 'YTD Target'
		dataType: string
		lineageTag: ac1ee975-89ce-44ee-8a93-a41292a632e8
		summarizeBy: none
		sourceColumn: YTD Target

		annotation SummarizationSetBy = Automatic

	column 'YTD Actual'
		dataType: string
		lineageTag: e2f73deb-22eb-481d-812e-2a1fae7d9bec
		summarizeBy: none
		sourceColumn: YTD Actual

		annotation SummarizationSetBy = Automatic

	column Column1
		dataType: string
		lineageTag: ef6d4f3a-382b-4790-83d8-200e6930420c
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition 2025Tooltip = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/Productivity2020/Shared%20Documents/General/Overall%20Productivity%20tracker/JIA%20Productivity%20tracker-Currently%20year.xlsx"), null, true),
				    LCIHUDDLE_Table = Source{[Item="LCIHUDDLE",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(LCIHUDDLE_Table,{{"Area", type text}, {"Fin Target", Int64.Type}, {"In Year Benefit", type number}, {"Gap", type number}, {"YTD Target", type any}, {"YTD Actual", type any}, {"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

