table DetailedProjects
	lineageTag: d68df17a-b4f0-4db5-a6ff-2e79beca0835

	column Category
		dataType: string
		lineageTag: c42710e2-be26-462d-b6ed-0a74e3fbf59c
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'ID Tracker'
		dataType: string
		lineageTag: 0b883308-a4cd-4cce-81d5-32c890c87988
		summarizeBy: none
		sourceColumn: ID Tracker

		annotation SummarizationSetBy = Automatic

	column Initiatives
		dataType: string
		lineageTag: d0ed7058-aa23-4735-98f0-5d54643c967b
		summarizeBy: none
		sourceColumn: Initiatives

		annotation SummarizationSetBy = Automatic

	column Comments
		dataType: string
		lineageTag: 21cfb8f6-6681-4a8c-9543-fda372da0879
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	column Status = ```
			
			VAR ActualMonth = WEEKNUM([SAT Actual])
			VAR PlanMonth = WEEKNUM([SAT Plan])
			VAR CurrentMonth = WEEKNUM(TODAY())
			VAR fx = 
			    IF(
			        ISBLANK('DetailedProjects'[SAT Plan]), "🟡", 
			        IF(
			            ISBLANK(ActualMonth),              
			                IF(CurrentMonth <= PlanMonth, "🟢", "🔴"),
			                IF(ActualMonth <= PlanMonth, "🟢", "🔴")
			        )
			    )
			RETURN
			    fx
			```
		lineageTag: cc73df64-a2b9-4d1f-9433-7e379096b463
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Site
		dataType: string
		lineageTag: 9ac4fb59-2ab5-4174-a4db-0f527f2bd7a2
		summarizeBy: none
		sourceColumn: Site

		annotation SummarizationSetBy = Automatic

	column 'SAT Plan'
		dataType: dateTime
		formatString: m/d/yyyy
		lineageTag: da2b9d37-cce9-4237-b5ae-2089d7988270
		summarizeBy: none
		sourceColumn: SAT Plan

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'SAT Actual'
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 2e5ebeeb-7146-4411-b7a4-6b0e03d745d0
		summarizeBy: none
		sourceColumn: SAT Actual

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 5cc18fb7-d525-4897-b1e5-87d9c6b6532c
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8a0c5d41-38f5-49fe-98bc-e0e730d63045
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Created
		dataType: dateTime
		formatString: Long Date
		lineageTag: 965174c1-688e-4e84-8c3b-edb37b6b46e4
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'SAT Lead'
		dataType: string
		lineageTag: d5a751e0-ce57-450b-a7c1-13d5ebcbc02e
		summarizeBy: none
		sourceColumn: SAT Lead

		annotation SummarizationSetBy = Automatic

	column 'Implement Lead'
		dataType: string
		lineageTag: a2166765-3c25-4b4f-8fd0-7a0d4e7f9330
		summarizeBy: none
		sourceColumn: Implement Lead

		annotation SummarizationSetBy = Automatic

	column UpdateOn
		dataType: dateTime
		formatString: m/d/yy
		lineageTag: 5b2cf55a-0969-413d-9508-41b1b8a9fd75
		summarizeBy: none
		sourceColumn: UpdateOn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column SATPlanWk = WEEKNUM('DetailedProjects'[SAT Plan])
		formatString: 0
		lineageTag: 0955a888-8332-45f4-8b41-3f22b2e491ea
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column WkActual = WEEKNUM(DetailedProjects[SAT Actual])
		formatString: 0
		lineageTag: b32b5326-cb69-4eb5-ab8b-719b9cbe8551
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column UpdatedOnWeek = WEEKNUM('DetailedProjects'[UpdateOn])
		formatString: 0
		lineageTag: 09e3dae6-a04e-4fc2-82ff-c0b1efe783cf
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Todaywk = WEEKNUM(TODAY(),21)
		formatString: 0
		lineageTag: 907a3902-f1f6-4827-ab44-df8f7da4d225
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column #
		dataType: string
		lineageTag: d0daccb9-6055-401f-9983-4dfa8b038bb5
		summarizeBy: none
		sourceColumn: #

		annotation SummarizationSetBy = Automatic

	column '2025 Saving'
		dataType: string
		lineageTag: 3c98bbf2-fb76-4896-b6cd-4df5b016de7d
		summarizeBy: none
		sourceColumn: 2025 Saving

		annotation SummarizationSetBy = Automatic

	column Projected
		dataType: string
		lineageTag: c0b46b56-42f0-4d27-886d-590f943e689e
		summarizeBy: none
		sourceColumn: Projected

		annotation SummarizationSetBy = Automatic

	column Jan
		dataType: string
		lineageTag: ece5df2e-adad-4361-861e-16af2b08eb8f
		summarizeBy: none
		sourceColumn: Jan

		annotation SummarizationSetBy = Automatic

	column Feb
		dataType: string
		lineageTag: 6c7c0f4b-4eb0-4f5a-83af-2f2344cf5bf2
		summarizeBy: none
		sourceColumn: Feb

		annotation SummarizationSetBy = Automatic

	column Mar
		dataType: string
		lineageTag: dba77369-5169-49c9-8925-d3e5def6cf96
		summarizeBy: none
		sourceColumn: Mar

		annotation SummarizationSetBy = Automatic

	column Apr
		dataType: string
		lineageTag: a9c3d951-5fdb-42ff-b987-ec5cba06acfb
		summarizeBy: none
		sourceColumn: Apr

		annotation SummarizationSetBy = Automatic

	column May
		dataType: string
		lineageTag: 775240b5-2cc2-47b7-aea9-ebc5c8776875
		summarizeBy: none
		sourceColumn: May

		annotation SummarizationSetBy = Automatic

	column Jun
		dataType: string
		lineageTag: 24b75da3-da42-4c9c-b086-a9c2c6e7a71c
		summarizeBy: none
		sourceColumn: Jun

		annotation SummarizationSetBy = Automatic

	column Jul
		dataType: string
		lineageTag: b24a2b74-e7a8-4a23-9d45-e9407228ae81
		summarizeBy: none
		sourceColumn: Jul

		annotation SummarizationSetBy = Automatic

	column Aug
		dataType: string
		lineageTag: d804a916-bc76-4bc9-852e-972ef309127e
		summarizeBy: none
		sourceColumn: Aug

		annotation SummarizationSetBy = Automatic

	column Sep
		dataType: string
		lineageTag: 3f5487aa-c3e3-4d82-9ef3-b68eab808224
		summarizeBy: none
		sourceColumn: Sep

		annotation SummarizationSetBy = Automatic

	column Oct
		dataType: string
		lineageTag: 5ac73a4f-c865-484c-923a-625f5aed3ba9
		summarizeBy: none
		sourceColumn: Oct

		annotation SummarizationSetBy = Automatic

	column Nov
		dataType: string
		lineageTag: a9970178-9b25-41ae-b9b4-51a3c64284c5
		summarizeBy: none
		sourceColumn: Nov

		annotation SummarizationSetBy = Automatic

	column Dec
		dataType: string
		lineageTag: f4494b87-ab79-47fa-95e2-bbd3c87ca21e
		summarizeBy: none
		sourceColumn: Dec

		annotation SummarizationSetBy = Automatic

	partition DetailedProjects = m
		mode: import
		source =
				let
				    Source = SharePoint.Tables("https://legogroup.sharepoint.com/sites/globalprocessingwheel", [Implementation="2.0", ViewMode="All"]),
				    #"57a704bc-26c2-4675-8669-afbe3cc3b773" = Source{[Id="57a704bc-26c2-4675-8669-afbe3cc3b773"]}[Items],
				    #"Changed Type" = Table.TransformColumnTypes(#"57a704bc-26c2-4675-8669-afbe3cc3b773",{{"SAT Plan", type date}, {"SAT Actual", type date}, {"UpdateOn", type date}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Created By", "Modified By", "Version", "Attachments", "Edit", "Type", "Item Child Count", "Folder Child Count", "Label setting", "Retention label", "Retention label Applied", "Label applied by", "Item is a Record", "App Created By", "App Modified By", "Content Type", "Compliance Asset Id", "Color Tag"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"Modified", type date}, {"Created", type date}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

