table 'Overall tracker'
	lineageTag: 7cbf42fb-50ea-45dd-aef0-c6cc8dc4731d

	column Sites
		dataType: string
		lineageTag: 3c84aa22-32b5-4e1b-b780-0f9bde10dea1
		summarizeBy: none
		sourceColumn: Sites

		annotation SummarizationSetBy = Automatic

	column Dept
		dataType: string
		lineageTag: fb5eca58-c9a4-4e04-b58c-c986d8679c92
		summarizeBy: none
		sourceColumn: Dept

		annotation SummarizationSetBy = Automatic

	column 'Project name'
		dataType: string
		lineageTag: a737a5f1-2c5b-4a2a-9487-f1b4305ccfd4
		summarizeBy: none
		sourceColumn: Project name

		annotation SummarizationSetBy = Automatic

	column 'Project leader'
		dataType: string
		lineageTag: 154dbd67-2681-402f-ae22-903fcdfb1de4
		summarizeBy: none
		sourceColumn: Project leader

		annotation SummarizationSetBy = Automatic

	column 'Cost bucket'
		dataType: string
		lineageTag: 1b259633-13d4-4773-9361-31819a776d02
		summarizeBy: none
		sourceColumn: Cost bucket

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 9793dc4a-0e65-4651-8b44-393b7042d43b
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Value Type'
		dataType: string
		lineageTag: 15ae3022-1427-4ee3-bdf7-77caa30baee7
		summarizeBy: none
		sourceColumn: Value Type

		annotation SummarizationSetBy = Automatic

	column 'YTD Saving(m DKK)'
		dataType: string
		lineageTag: e4fdb0e8-0cf2-4d2c-bdbc-4243c0c200ba
		summarizeBy: none
		sourceColumn: YTD Saving(m DKK)

		annotation SummarizationSetBy = Automatic

	column 'Total Target(m DKK)'
		dataType: string
		lineageTag: 01665202-f498-4f3d-9c15-fbacf29efd60
		summarizeBy: none
		sourceColumn: Total Target(m DKK)

		annotation SummarizationSetBy = Automatic

	column IL
		dataType: string
		lineageTag: 23e602fe-50ad-46d3-8fb7-564d9aa142c6
		summarizeBy: none
		sourceColumn: IL

		annotation SummarizationSetBy = Automatic

	column 'Carry over average saving/month to 2025'
		dataType: string
		lineageTag: bbc6595d-fa86-477d-92cf-fa69b2087eff
		summarizeBy: none
		sourceColumn: Carry over average saving/month to 2025

		annotation SummarizationSetBy = Automatic

	column 'Carry over months in 2025'
		dataType: string
		lineageTag: 005c431b-4d1a-4ba9-bca9-d7818107a01b
		summarizeBy: none
		sourceColumn: Carry over months in 2025

		annotation SummarizationSetBy = Automatic

	column ID_General
		dataType: string
		lineageTag: 3d861d28-971b-4059-b9c2-3705a6252c8a
		summarizeBy: none
		sourceColumn: ID_General

		annotation SummarizationSetBy = Automatic

	column Comments
		dataType: string
		lineageTag: 37068af7-7b4e-4ca3-b217-946f8841a306
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	column NO
		dataType: string
		lineageTag: ee07c048-3771-4cc9-8b29-89f20ded79d3
		summarizeBy: none
		sourceColumn: NO

		annotation SummarizationSetBy = Automatic

	column MonthNum
		dataType: int64
		formatString: 0
		lineageTag: 047e5176-6ab0-473e-9b99-482d08877c95
		summarizeBy: none
		sourceColumn: MonthNum

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: f4ec6202-946b-4cc4-be61-e097c7135305
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Month = ```
			
			SWITCH(
			  'Overall tracker'[MonthNum],
			  1, "Jan", 2, "Feb", 3, "Mar", 4, "Apr",
			  5, "May", 6, "Jun", 7, "Jul", 8, "Aug",
			  9, "Sep",10, "Oct",11, "Nov",12, "Dec",
			  BLANK()
			)
			
			```
		lineageTag: f3c79748-68c4-43ca-bd45-f951b84146ac
		summarizeBy: none
		sortByColumn: MonthNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column IL_
		dataType: string
		lineageTag: 62fc2275-9cb6-447b-ba4b-5570aa70e115
		summarizeBy: none
		sourceColumn: IL_

		annotation SummarizationSetBy = Automatic

	partition 'Overall tracker' = m
		mode: import
		source = ```
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/Productivity2020/Shared%20Documents/General/Overall%20Productivity%20tracker/JIA%20Productivity%20tracker-Currently%20year.xlsx"), null, true),
				    #"Overall tracker_Sheet" = Source{[Item="Overall tracker",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Overall tracker_Sheet", [PromoteAllScalars=true]),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Promoted Headers", {"Area", "Dept.", "Project name", "Project leader", "Cost bucket", "Category", "Value Type", "YTD Saving#(lf)(m DKK)", "Total Target#(lf)(m DKK)", "IL", "Carry over average saving/month to 2025", "Carry over months in 2025", "ID_General", "Comments", "NO"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Month"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Month", Int64.Type}, {"Value", type number}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type1", {{"Value", 0}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Replaced Errors","Packing","NYI",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Processing","KOM",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value1","LFAC","LOM",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value4","Supporting","LOM",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Moulding","JIA",Replacer.ReplaceText,{"Area"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Replaced Value3",{{"Area", "Sites"}, {"Dept.", "Dept"}}),
				    #"Replaced Values"= Table.ReplaceValue(
				    #"Renamed Columns1",
				    each [Dept],
				    each List.ReplaceMatchingItems(
				        {[Dept]}, 
				        {{"Management", "Moulding"}, {"Processing", "HBW"},{"Finalpack", "Moulding"},{"Maintenance", "Machine Maintenance"},{"MWH", "Mould Maint"},{"NPI", "MPE&E"},{"Others", "Production"},{"Prepack", "Repair & Maintenance"},{"LFAC", "Production"}}
				    ){0},
				    Replacer.ReplaceValue,
				    {"Dept"}
				),
				    #"Renamed Columns2" = Table.RenameColumns(#"Replaced Values",{{"Month", "MonthNum"}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns2", "IL", "IL - Copy"),
				    #"Renamed Columns3" = Table.RenameColumns(#"Duplicated Column",{{"IL - Copy", "IL_"}}),
				    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Renamed Columns3", {{"IL_", each Text.BeforeDelimiter(_, "-"), type text}}),
				    #"Cleaned Text" = Table.TransformColumns(#"Extracted Text Before Delimiter",{{"IL_", Text.Clean, type text}})
				in
				    #"Cleaned Text"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

