table Target_Plant
	lineageTag: b26f87d8-2be1-44cd-9916-1766e99c64e4

	column Site
		dataType: string
		lineageTag: 64555274-1945-4d46-9b79-82e9aa6e58b1
		summarizeBy: none
		sourceColumn: Site

		annotation SummarizationSetBy = Automatic

	column Target
		dataType: double
		lineageTag: 450c4cdb-9b5b-4898-a69f-68146db792c6
		summarizeBy: sum
		sourceColumn: Target

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Target_Plant = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8vJ0VNJRslCK1YlW8vb3BbJNwGwfMNsYzPaL9ASyLZViYwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Site = _t, Target = _t])
				in
				    Source

	annotation PBI_ResultType = Table

