table '2026 ProductivityUpdate_IL'
	lineageTag: 1b1e877b-7b95-4dda-a3cf-941b8fa8cbab

	measure Project_Num = SUM('2026 ProductivityUpdate_IL'[Value])
		formatString: 0
		lineageTag: ce9d748e-a4d9-42d6-87a8-ac8cf4d99d64

	column 'Update Week'
		dataType: string
		lineageTag: d36b597d-7afe-4bf8-8aa5-628cca5cfe01
		summarizeBy: none
		sourceColumn: Update Week

		annotation SummarizationSetBy = Automatic

	column 'Business area/Technology'
		dataType: string
		lineageTag: 4fe8562b-ec77-4c37-9ac5-affa18bc7bf6
		summarizeBy: none
		sourceColumn: Business area/Technology

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 78fd48a8-0ecc-4831-ad11-d1e738a74020
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column IL
		dataType: string
		lineageTag: 4c88ac64-1fa6-4456-b3c0-16423800f2cd
		summarizeBy: none
		sourceColumn: IL

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 5c942cdd-0c55-4e71-83b9-61fd140bf64e
		summarizeBy: sum
		sourceColumn: Value

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition '2026 ProductivityUpdate_IL' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALCI/Shared%20Documents/General/01_Department%20Info/01_Digital%20Huddle/06_KPI/2025/DigitalHuddle/2026%20Initiative%20update.xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(Table1_Table,{"Generate initiatives"}),
				    #"Unpivoted Only Selected Columns" = Table.Unpivot(#"Removed Columns", {"IL0-2", "IL3-5"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Only Selected Columns",{{"Attribute", "IL"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

