table '2026 ProductivityUpdate'
	lineageTag: 478bf9ae-8b81-43db-9e94-450706b698ef

	measure Num_Initiatives =
			CALCULATE(
			    SUM('2026 ProductivityUpdate'[Generate initiatives])
			)
		formatString: 0
		lineageTag: 8185c45d-683b-4528-a504-1bff288bbcd7

	column 'Update Week'
		dataType: string
		lineageTag: c4d1f450-029f-4689-b811-0268bd066762
		summarizeBy: none
		sourceColumn: Update Week

		annotation SummarizationSetBy = Automatic

	column 'Business area/Technology'
		dataType: string
		lineageTag: e9376361-6232-4e4f-b8e5-3e45e96afacb
		summarizeBy: none
		sourceColumn: Business area/Technology

		annotation SummarizationSetBy = Automatic

	column 'Generate initiatives'
		dataType: int64
		formatString: 0
		lineageTag: 2ff8e8e9-0d63-4cf1-9db8-3060c1756e31
		summarizeBy: sum
		sourceColumn: Generate initiatives

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: fe36c909-6baf-4111-9459-fb1d95c5c75d
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition '2026 ProductivityUpdate' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALCI/Shared%20Documents/General/01_Department%20Info/01_Digital%20Huddle/06_KPI/2025/DigitalHuddle/2026%20Initiative%20update.xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(Table1_Table,{"IL0-2", "IL3-5"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

