table EHS
	lineageTag: 9a14b0f5-ee83-4bc3-b31a-834be2355c68

	measure 'EHS Actual' = CALCULATE( SUM('EHS'[Value]), 'EHS'[Type]="Actual")
		formatString: 0
		lineageTag: ab278a49-9f17-42d6-af4b-45e3bcad0d4a

	column Owner
		dataType: string
		lineageTag: b1adf2bd-2c4a-4d4c-b379-c565ba065795
		summarizeBy: none
		sourceColumn: Owner

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		lineageTag: 033a2d9e-cb82-4fa4-9e2a-d09120e52c3f
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 4039a049-e355-438d-9759-045ed096a6db
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: e796d3a5-8d4f-4acf-b09a-fcad94377f7f
		summarizeBy: sum
		sourceColumn: Value

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition EHS = m
		mode: import
		source =
				let
				    源 = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALCI/Shared%20Documents/General/01_Department%20Info/01_Digital%20Huddle/06_KPI/2023/P-KPI%202023_RZ_LCI%20EHS%20V0.xlsx"), null, true),
				    EHS_Sheet = 源{[Item="EHS",Kind="Sheet"]}[Data],
				    提升的标题 = Table.PromoteHeaders(EHS_Sheet, [PromoteAllScalars=true]),
				    更改的类型 = Table.TransformColumnTypes(提升的标题,{{"Owner", type text}, {"Item", type text}, {"Actual", Int64.Type}, {"Target", Int64.Type}, {"Achieved rate", type number}}),
				    #"Filtered Rows" = Table.SelectRows(更改的类型, each ([Owner] <> null)),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Achieved rate"}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Columns", {"Item", "Owner"}, "Type", "Value")
				in
				    #"Unpivoted Other Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

