table Productivity_PFP
	isHidden
	lineageTag: 34277b8b-888b-4dad-ac0a-950d28163af1

	column IL
		dataType: string
		isHidden
		lineageTag: 64788477-ab60-47da-a7d8-4a4a50701520
		summarizeBy: none
		sourceColumn: IL

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c8de539e-17ec-4bf8-91c0-0dcecb8b3360
		summarizeBy: sum
		sourceColumn: Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		isHidden
		lineageTag: 95d30344-003c-43d8-bb44-0468349c8644
		summarizeBy: sum
		sourceColumn: Value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Date created'
		dataType: string
		isHidden
		lineageTag: 322d02da-edb9-40fa-b8d3-0cf70a8cb946
		summarizeBy: none
		sourceColumn: Date created

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		isHidden
		lineageTag: 47d4f9f9-32c2-4ef8-8518-62353a0901b5
		summarizeBy: none
		sourceColumn: Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Value Type'
		dataType: string
		isHidden
		lineageTag: 3c87cdae-6516-4054-b751-4fad6f7ac6f8
		summarizeBy: none
		sourceColumn: Value Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 165e70bd-c533-4ab6-a8c9-9b8fb42464e8
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	partition Productivity_PFP = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows([]),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"7c90095b-31de-43da-b11e-e3c19e33be7d" = Workspaces{[workspaceId="7c90095b-31de-43da-b11e-e3c19e33be7d"]}[Data],
				    #"8b87b6cf-63ec-405d-9c19-2ab933c27890" = #"7c90095b-31de-43da-b11e-e3c19e33be7d"{[dataflowId="8b87b6cf-63ec-405d-9c19-2ab933c27890"]}[Data],
				    pfp_ = #"8b87b6cf-63ec-405d-9c19-2ab933c27890"{[entity="pfp",version=""]}[Data],
				    #"Removed Columns1" = Table.RemoveColumns(pfp_,{"Index"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns1", "Key", each [Month Name] &"-"& [IL LEVEL]),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Value Type", each "PFP"),
				    #"Inserted Month" = Table.AddColumn(#"Added Custom1", "Index", each Date.Month([Date created]), Int64.Type),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Month",{"Date created", "TECHNOLOGY"}),
				    #"Added Custom2" = Table.AddColumn(#"Removed Columns", "Area", each "PFP"),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom2",{{"PfP", "Value"}, {"IL LEVEL", "IL"}, {"Month Name", "Date created"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

