table Productivity_Overview
	lineageTag: ba2fdf56-5d74-41c2-8697-868aaeae1e90

	column Month
		dataType: string
		lineageTag: db0b6dce-f150-40f8-a588-f24f049d63ba
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column IL
		dataType: string
		lineageTag: 6c87bde1-1a5f-4d9f-a4e9-0ebb166e176d
		summarizeBy: none
		sourceColumn: IL

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 389af31e-c4ec-4380-b02b-7022e9cf67e5
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column key
		dataType: string
		lineageTag: 409cff42-c62e-49fb-841e-1d0b665aa28f
		summarizeBy: none
		sourceColumn: key

		annotation SummarizationSetBy = Automatic

	partition Productivity_Overview = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows([]),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"7c90095b-31de-43da-b11e-e3c19e33be7d" = Workspaces{[workspaceId="7c90095b-31de-43da-b11e-e3c19e33be7d"]}[Data],
				    #"8b87b6cf-63ec-405d-9c19-2ab933c27890" = #"7c90095b-31de-43da-b11e-e3c19e33be7d"{[dataflowId="8b87b6cf-63ec-405d-9c19-2ab933c27890"]}[Data],
				    Overview_ = #"8b87b6cf-63ec-405d-9c19-2ab933c27890"{[entity="Overview",version=""]}[Data],
				    #"Added Custom" = Table.AddColumn(Overview_, "key", each [Month]&"-"&[IL])
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

