table 'Abnormal Finding'
	lineageTag: 3131e26a-a704-4384-9ca8-6429e1b4a5e1

	column Findings
		dataType: string
		lineageTag: c1783614-2e47-4198-8ce8-a1d6815c7916
		summarizeBy: none
		sourceColumn: Findings

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: c4964a9e-d6c7-49d8-88b3-4a19a6109fd3
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FindingCategory
		dataType: string
		lineageTag: 465fa40a-ca0c-48b0-b494-4d1cbdc0affb
		summarizeBy: none
		sourceColumn: FindingCategory

		annotation SummarizationSetBy = Automatic

	column 'Abnormal Finding Area'
		dataType: string
		lineageTag: 93613054-40e3-4e59-96b5-3a574427df11
		summarizeBy: none
		sourceColumn: Abnormal Finding Area

		annotation SummarizationSetBy = Automatic

	column 'Non ESPA Finding Area'
		dataType: string
		lineageTag: 82b19ee1-9735-48b7-a095-3d29545b7c2c
		summarizeBy: none
		sourceColumn: Non ESPA Finding Area

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: string
		lineageTag: 0e61090b-aae8-4e46-85ec-b6c3cd281429
		summarizeBy: none
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = Automatic

	column 'ESPA Finding Area'
		dataType: string
		lineageTag: a3024cbd-a7c1-42c2-9410-0e3fffb3151c
		summarizeBy: none
		sourceColumn: ESPA Finding Area

		annotation SummarizationSetBy = Automatic

	column Weekname
		dataType: string
		lineageTag: 3333ed2c-fbec-4c68-b449-1b4f8a9b107c
		summarizeBy: none
		sourceColumn: Weekname

		annotation SummarizationSetBy = Automatic

	partition 'Abnormal Finding' = m
		mode: import
		source =
				let
				    Source = Security_Q,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([FindingCategory] = "Abnormal Finding (ESPA)" or [FindingCategory] = "Abnormal Finding (Non-ESPA)")),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Findings", "Date", "FindingCategory", "ESPA Finding Area", "Abnormal Finding Area", "Non ESPA Finding Area", "Weekname", "DayOfMonth"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

