table 'Complaint & Appreciation'
	isHidden
	lineageTag: edc4d454-2ee2-4638-b657-476e79206cfd

	column Findings
		dataType: string
		isHidden
		lineageTag: 8dbf4cdc-86ea-49ca-a66c-046d7a5df1ac
		summarizeBy: none
		sourceColumn: Findings

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: e9af1f30-9ff2-4b66-9d38-d654a911e1d3
		summarizeBy: none
		sourceColumn: Created

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: d6b3da17-6fde-45b9-80a3-f87aeb08a158
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FindingCategory
		dataType: string
		isHidden
		lineageTag: a7bb9f74-f4d2-4a65-81cf-0a363cf4a53a
		summarizeBy: none
		sourceColumn: FindingCategory

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Abnormal Finding Area'
		dataType: string
		isHidden
		lineageTag: aaf711d4-7cfd-4b02-952d-626a7f90a32f
		summarizeBy: none
		sourceColumn: Abnormal Finding Area

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Non ESPA Finding Area'
		dataType: string
		isHidden
		lineageTag: 03c07bbc-938e-468c-984c-d7277bb23850
		summarizeBy: none
		sourceColumn: Non ESPA Finding Area

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Alarm/ False Alarm'
		dataType: string
		isHidden
		lineageTag: 5308deb2-35b0-450f-9582-7d2c609ac3f7
		summarizeBy: none
		sourceColumn: Alarm/ False Alarm

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Alarm Type'
		dataType: string
		isHidden
		lineageTag: 8e846dc6-38a2-4bef-a4e5-4d39041c7ce8
		summarizeBy: none
		sourceColumn: Alarm Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Complaint/Appreciation
		dataType: string
		isHidden
		lineageTag: 12d93d16-d6d1-4303-91d1-75930d407850
		summarizeBy: none
		sourceColumn: Complaint/Appreciation

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ca08b159-5c16-4d1a-97dc-12684351d9b5
		summarizeBy: count
		sourceColumn: ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Color Tag'
		dataType: string
		isHidden
		lineageTag: 642036ea-d2d9-403e-b3c5-a110f026b269
		summarizeBy: none
		sourceColumn: Color Tag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Compliance Asset Id'
		dataType: string
		isHidden
		lineageTag: 22822c26-0a23-4ffa-a6df-1db2a8cafe71
		summarizeBy: none
		sourceColumn: Compliance Asset Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		isHidden
		lineageTag: e7468692-c89a-4650-a303-3c7c810f3be5
		summarizeBy: none
		sourceColumn: Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CorA_Area
		dataType: string
		isHidden
		lineageTag: 70c374db-217b-44bb-9f64-6a6efbcd2471
		summarizeBy: none
		sourceColumn: CorA_Area

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Content Type'
		dataType: string
		isHidden
		lineageTag: c4aabf28-00e4-41ad-baac-664f014d73ec
		summarizeBy: none
		sourceColumn: Content Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 22d0b4a2-4497-4fc1-91f3-f9f74cc4a09e
		summarizeBy: none
		sourceColumn: Modified

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Modified By'
		dataType: string
		isHidden
		lineageTag: 17dfe006-c978-40ac-92ea-bcbc06d620ff
		summarizeBy: none
		sourceColumn: Modified By

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		isHidden
		lineageTag: d59cf492-9f0b-421c-8f07-a1540ea346f0
		summarizeBy: none
		sourceColumn: Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Child Count'
		dataType: string
		isHidden
		lineageTag: 39dde117-b918-415b-9efc-6ca238b8842a
		summarizeBy: none
		sourceColumn: Item Child Count

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Folder Child Count'
		dataType: string
		isHidden
		lineageTag: cac03b1d-29d9-406c-8ad2-ab8b55d22e96
		summarizeBy: none
		sourceColumn: Folder Child Count

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Label setting'
		dataType: string
		isHidden
		lineageTag: 36b96659-b77a-4007-b6d9-d77489845441
		summarizeBy: none
		sourceColumn: Label setting

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Retention label'
		dataType: string
		isHidden
		lineageTag: 0007e3d6-ceec-496c-880b-33c6144d190c
		summarizeBy: none
		sourceColumn: Retention label

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Retention label Applied'
		dataType: string
		isHidden
		lineageTag: e6ec9711-bdab-4c6d-a4b2-71f1fd90c01a
		summarizeBy: none
		sourceColumn: Retention label Applied

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: string
		isHidden
		lineageTag: e6fea5be-3b1b-40c3-80a7-af0969a76492
		summarizeBy: none
		sourceColumn: DayOfMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'ESPA Finding Area'
		dataType: string
		isHidden
		lineageTag: 8f97a006-d7db-458d-9562-457e075c4311
		summarizeBy: none
		sourceColumn: ESPA Finding Area

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Created By'
		dataType: string
		isHidden
		lineageTag: 03f86d9f-f08b-460c-9478-d56bf06536ba
		summarizeBy: none
		sourceColumn: Created By

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Attachments
		dataType: string
		isHidden
		lineageTag: e802bd45-017d-489a-9711-ce786f582772
		summarizeBy: none
		sourceColumn: Attachments

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Weekname
		dataType: string
		isHidden
		lineageTag: 5622b6a3-16cc-4d2c-8059-35bf24923099
		summarizeBy: none
		sourceColumn: Weekname

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Radar_Location
		dataType: string
		lineageTag: dcc961de-3a29-4bcb-98cf-ae095fae9a50
		summarizeBy: none
		sourceColumn: Radar_Location

		annotation SummarizationSetBy = Automatic

	column 'No.'
		dataType: double
		lineageTag: 3d8b4068-3e63-4053-90f4-777e168ffbc1
		summarizeBy: sum
		sourceColumn: No.

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Times
		dataType: string
		lineageTag: 2afdb31b-d804-4ee9-9f7a-456d1fa72ad9
		summarizeBy: none
		sourceColumn: Times

		annotation SummarizationSetBy = Automatic

	column Location_Incident
		dataType: string
		lineageTag: 640cd8ea-02ce-43f6-aab1-2077ea58ed9e
		summarizeBy: none
		sourceColumn: Location_Incident

		annotation SummarizationSetBy = Automatic

	column Equipment
		dataType: string
		lineageTag: a4941681-826c-4a4b-8910-f9bbd1fa24c2
		summarizeBy: none
		sourceColumn: Equipment

		annotation SummarizationSetBy = Automatic

	column IncidentFindingNumber
		dataType: string
		lineageTag: e47b6817-604c-4d01-ae3b-2cda4cd40526
		summarizeBy: none
		sourceColumn: IncidentFindingNumber

		annotation SummarizationSetBy = Automatic

	column IncidentFindingStatus
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b72e3568-79b2-44be-aa2e-928db3e40d32
		summarizeBy: none
		sourceColumn: IncidentFindingStatus

		annotation SummarizationSetBy = Automatic

	partition 'Complaint & Appreciation' = m
		mode: import
		source =
				let
				    Source = Security_Q,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([FindingCategory] = "Complaint & Appreciation"))
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

