table 'Complaint To Aden (Q7)'
	lineageTag: 6c80e63e-fa82-4d58-8aa3-a8a257738b37

	column NO
		dataType: string
		lineageTag: 2dc28712-eb51-4d6a-b782-6cb202169d62
		summarizeBy: none
		sourceColumn: NO

		annotation SummarizationSetBy = Automatic

	column Mon
		dataType: string
		lineageTag: b030c110-5673-4c77-966d-ce489e8dfbf8
		summarizeBy: none
		sourceColumn: Mon

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 37ee8dce-918a-4150-bcc8-3499f14c3ade
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Scope
		dataType: string
		lineageTag: 28bcbe8b-4381-49d5-80b6-b1a8f04ee8bd
		summarizeBy: none
		sourceColumn: Scope

		annotation SummarizationSetBy = Automatic

	column 'Where '
		dataType: string
		lineageTag: 883a0b8d-b878-4fbd-9d57-2de764abb7fa
		summarizeBy: none
		sourceColumn: "Where "

		annotation SummarizationSetBy = Automatic

	column From
		dataType: string
		lineageTag: 986f7737-89b9-4e94-bb0d-33b170066645
		summarizeBy: none
		sourceColumn: From

		annotation SummarizationSetBy = Automatic

	column To
		dataType: string
		lineageTag: 45d859b0-11be-456b-9def-6b661d02c90f
		summarizeBy: none
		sourceColumn: To

		annotation SummarizationSetBy = Automatic

	column What
		dataType: string
		lineageTag: a7f11ee0-2623-425e-8747-552983e9f06d
		summarizeBy: none
		sourceColumn: What

		annotation SummarizationSetBy = Automatic

	column 'Action Taken By'
		dataType: string
		lineageTag: 28874412-3406-408d-864d-4dcd20dbfb73
		summarizeBy: none
		sourceColumn: Action Taken By

		annotation SummarizationSetBy = Automatic

	column Details
		dataType: string
		lineageTag: e6ee7a9e-d325-47b4-9283-a7bc8d0c275f
		summarizeBy: none
		sourceColumn: Details

		annotation SummarizationSetBy = Automatic

	column Sataus
		dataType: string
		lineageTag: 829ab90a-0e15-4faf-85f8-2d994775116a
		summarizeBy: none
		sourceColumn: Sataus

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 419b4923-5b45-4045-a23a-6c43bdf1ad20
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	partition 'Complaint To Aden (Q7)' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/CHJiaxingSecurity/Shared%20Documents/00%20Digital%20Huddle/Digital%20Huddle%20(Excel%E7%89%88-%E8%AF%95%E8%BF%90%E8%A1%8C%EF%BC%89/04%20Complaint%202025.xlsx")),
				    Q7_sheet = Source{[Item="Q7",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(Q7_sheet,2),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers",{"Column13", "Column14", "Column15", "Column16", "Column17", "Area", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Total"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Columns", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Blank Rows",{{"Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

