table 'Digital_Huddle PDCA'
	lineageTag: 455677c5-d7c9-4b60-9c30-642f296c9db0

	column ID
		dataType: string
		isNullable: false
		sourceProviderType: int
		lineageTag: 97f1e372-bdb0-4291-bd14-6a7ead72b767
		summarizeBy: none
		sourceColumn: ID

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Department_ID
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 7f25923a-0d86-458c-85d6-b6ec56f4b34f
		summarizeBy: count
		sourceColumn: Department_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date_of_record
		dataType: dateTime
		isNullable: false
		formatString: General Date
		lineageTag: 76f91e36-79d4-479d-8bae-762f1dec9964
		summarizeBy: none
		sourceColumn: Date_of_record

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Recorded_By
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: 0ce3013f-74c0-43e8-bd49-91fa42e9530a
		summarizeBy: none
		sourceColumn: Recorded_By

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Concern
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(max)
		lineageTag: 484a3ac5-3611-4cec-b0b7-9a57de5861f2
		summarizeBy: none
		sourceColumn: Concern

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Concern_Modified_by
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: 776338aa-f8ed-4b90-8a54-6ea5774058c1
		summarizeBy: none
		sourceColumn: Concern_Modified_by

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Concern_Modified_at
		dataType: dateTime
		formatString: General Date
		lineageTag: e0416d06-4497-4de0-950a-7b27ebb0dbae
		summarizeBy: none
		sourceColumn: Concern_Modified_at

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Containment
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: c6a8b02e-48f6-4d78-8285-58839f636ce4
		summarizeBy: none
		sourceColumn: Containment

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Containment_Responsible
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: 7b0f7a27-0893-41d8-bc9d-660b11e5e7ca
		summarizeBy: none
		sourceColumn: Containment_Responsible

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Containment_Check_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 441df8c8-334c-4cf4-b6f3-e70eefc50820
		summarizeBy: none
		sourceColumn: Containment_Check_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Containment_Status
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: b1d21343-fb6e-4d8d-b807-44911bbdd1f3
		summarizeBy: sum
		sourceColumn: Containment_Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Containment_Modified_by
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: 7d5ee003-4d0f-4fd2-88bb-2b6e6a9e97d0
		summarizeBy: none
		sourceColumn: Containment_Modified_by

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Containment_Modified_at
		dataType: dateTime
		formatString: General Date
		lineageTag: bbd28cbc-ac3a-437b-a39d-96f14d9b1871
		summarizeBy: none
		sourceColumn: Containment_Modified_at

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Countermeasure
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 84a23574-f92f-403e-a580-a51013f4c330
		summarizeBy: none
		sourceColumn: Countermeasure

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Countermeasure_Responsible
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: e350bf6e-c564-4c01-8ad0-ae8af1550cef
		summarizeBy: none
		sourceColumn: Countermeasure_Responsible

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Countermeasure_Act_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c8e89dd8-4751-4005-9760-e45f7083f2a9
		summarizeBy: none
		sourceColumn: Countermeasure_Act_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Countermeasure_Status
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 90716104-6232-4ce8-8451-407d23c25709
		summarizeBy: sum
		sourceColumn: Countermeasure_Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Countermeasure_Modified_by
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: e9eea2bd-dd1d-4fd0-9294-46b61fd0a4dc
		summarizeBy: none
		sourceColumn: Countermeasure_Modified_by

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Countermeasure_Modified_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 14d3a8ac-09be-4122-9a01-4403825042a1
		summarizeBy: none
		sourceColumn: Countermeasure_Modified_at

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column GLS_ID
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 4735fda1-59be-416c-82fc-1ca34fbf9dec
		summarizeBy: count
		sourceColumn: GLS_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Archived
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: df3c6c52-d34e-46eb-a7bf-e43ab21146a6
		summarizeBy: none
		sourceColumn: Archived

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SQDCP_O_TYPE
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: 2b11646f-246d-4b7a-a1d9-7c47ae99f66a
		summarizeBy: none
		sourceColumn: SQDCP_O_TYPE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Raised_by
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: 8fbb38a3-02e6-44dd-ba2b-f1ed5555e1ab
		summarizeBy: none
		sourceColumn: Raised_by

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Shift
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: 3df3d3b3-5526-4d4c-8921-e4dd8d493eb9
		summarizeBy: none
		sourceColumn: Shift

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PDCA_Area
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: 8a13269b-ba37-4bfe-b276-c269bc094cad
		summarizeBy: none
		sourceColumn: PDCA_Area

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column shift_handover
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: f28174af-6e05-4841-94eb-03f1f45c450c
		summarizeBy: none
		sourceColumn: shift_handover

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Cause
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 8edc2b80-c7af-4f00-bdf6-a94537ea7435
		summarizeBy: none
		sourceColumn: Cause

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Digital_Huddle PDCA' = m
		mode: import
		source =
				let
				    Source = Sql.Database("btmstdfdevbiman.database.windows.net", "Digital_Huddle_JIA"),
				    dbo_Digital_Huddle.PDCA = Source{[Schema="dbo",Item="Digital_Huddle.PDCA"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_Digital_Huddle.PDCA, each ([Department_ID] = 43)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Date_of_record", type datetime}, {"Containment_Check_date", type date}, {"Concern_Modified_at", type datetime}, {"Containment_Modified_at", type datetime}, {"Countermeasure_Act_date", type date}, {"Countermeasure_Modified_at", type datetime}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

