table dPene
	lineageTag: cc359065-1bb4-4375-bcbc-68607667f5f7

	column dPene
		dataType: string
		lineageTag: e7d126ff-9079-4ba8-af50-cbe3633eae54
		summarizeBy: none
		sourceColumn: dPene
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: 2cb5c946-759e-4a12-80d4-3bcf2d72d8a3
		summarizeBy: none
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	partition dPene = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wcg0OcFTSUTJUitWJVvLLz9OFChiBBXycnYFsY6XYWAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Column1", "dPene"}, {"Column2", "Sort"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

