table 'Incident Finding'
	lineageTag: 3b15c03e-a70b-4a81-942e-486b4ddfe824

	column Findings
		dataType: string
		lineageTag: f5e8304f-4089-48db-b2a6-01b7bae757b2
		summarizeBy: none
		sourceColumn: Findings

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 35beb30d-57cc-43ba-bd14-e7b98f5fb50b
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FindingCategory
		dataType: string
		lineageTag: d9aaea0e-a6a8-4367-bb34-e937a7e2e6c6
		summarizeBy: none
		sourceColumn: FindingCategory

		annotation SummarizationSetBy = Automatic

	column 'Non ESPA Finding Area'
		dataType: string
		lineageTag: 99441647-ef7c-47cf-bd81-55b4652e6345
		summarizeBy: none
		sourceColumn: Non ESPA Finding Area

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: string
		lineageTag: a18bc534-c9ef-40dc-8e28-7fc69205ada3
		summarizeBy: none
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = Automatic

	column ESPAFindingArea_num
		dataType: int64
		formatString: 0
		lineageTag: 3c773e25-8a1d-4218-aad7-fbc05726c942
		summarizeBy: sum
		sourceColumn: ESPAFindingArea_num

		annotation SummarizationSetBy = Automatic

	column 'ESPA Finding Area'
		dataType: string
		lineageTag: 5418d132-985c-4ea3-b384-7b6caa1ad296
		summarizeBy: none
		sourceColumn: ESPA Finding Area

		annotation SummarizationSetBy = Automatic

	column Weekname
		dataType: string
		lineageTag: 25a81108-91db-4dd1-8196-220796e3193b
		summarizeBy: none
		sourceColumn: Weekname

		annotation SummarizationSetBy = Automatic

	column IncidentFindingNumber
		dataType: string
		lineageTag: 04d86303-1410-4e47-914a-a473ea8cda3b
		summarizeBy: none
		sourceColumn: IncidentFindingNumber

		annotation SummarizationSetBy = Automatic

	column IncidentFindingStatus
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a864817a-61a4-4ec6-ac03-ac5276cdeeb8
		summarizeBy: none
		sourceColumn: IncidentFindingStatus

		annotation SummarizationSetBy = Automatic

	column Status =
			
			IF('Incident Finding'[IncidentFindingStatus]=True,
			"Closed",
			"Open"
			)
		lineageTag: 7d622313-5ba5-4d57-b25f-eb77448163c1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Incident Finding' = m
		mode: import
		source =
				let
				    Source = Security_Q,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([FindingCategory] = "Incident Finding (ESPA)" or [FindingCategory] = "Incident Finding (Non-ESPA)")),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Filtered Rows", "ESPA Finding Area", "ESPA Finding Area  - Copy"),
				    #"Extracted Text After Delimiter" = Table.TransformColumns(#"Duplicated Column", {{"ESPA Finding Area  - Copy", each Text.AfterDelimiter(_, "A"), type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Extracted Text After Delimiter",{{"ESPA Finding Area  - Copy", "ESPAFindingArea_num"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Findings", "Created", "Date", "FindingCategory", "ESPA Finding Area", "ESPAFindingArea_num", "Abnormal Finding Area", "Non ESPA Finding Area", "Alarm/ False Alarm", "Alarm Type", "ID",  "Color Tag", "Compliance Asset Id", "Status",  "CorA_Area", "Content Type", "Modified", "Modified By",  "Type", "Item Child Count", "Folder Child Count", "Label setting", "Retention label", "Retention label Applied",  "DayOfMonth"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Reordered Columns",{{"ESPAFindingArea_num", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Findings", "Date", "FindingCategory", "ESPA Finding Area", "ESPAFindingArea_num", "Non ESPA Finding Area", "IncidentFindingNumber", "IncidentFindingStatus", "Weekname", "DayOfMonth"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

