table 'Monitor Skill Matrix'
	lineageTag: 5c3555a9-3dc8-480e-9226-07a2fd1374e8

	column 'Skills Matrix Gap'
		dataType: string
		lineageTag: de775b83-73f9-4473-bdfd-d13e83b344ec
		summarizeBy: none
		sourceColumn: Skills Matrix Gap

		annotation SummarizationSetBy = Automatic

	column 'Completion (vs. targets)'
		dataType: double
		formatString: 0%;-0%;0%
		lineageTag: a00b1c39-ab64-492d-8ac1-42294c148d94
		summarizeBy: sum
		sourceColumn: Completion (vs. targets)

		annotation SummarizationSetBy = Automatic

	partition 'Monitor Skill Matrix' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/CHJiaxingSecurity/Shared Documents/08 LCC%E6%97%A5%E5%B8%B8%E7%AE%A1%E7%90%86/LCC Skill Matrix/Monitor Skill Matrix 2.0 (Aden).xlsx"), null, true),
				    #"Skill Matrix 2.0_Sheet" = Source{[Item="Skill Matrix 2.0",Kind="Sheet"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(#"Skill Matrix 2.0_Sheet",{"Column42", "Column43"}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Removed Other Columns", {"Column42"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Errors", each ([Column42] <> null)),
				    #"Kept Last Rows" = Table.LastN(#"Filtered Rows", 2),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Kept Last Rows", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Completion #(lf)(vs. targets)", Percentage.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

