table 'Night Inspection'
	lineageTag: b651aec2-5710-4d0b-aaea-597b32149f29

	measure YTD = "YTD"
		lineageTag: efd98519-ea5a-47a8-8f41-791c2e9ed962

	column Month
		dataType: string
		lineageTag: 022b2b55-feb6-450d-8825-be5ca71aa844
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Plan
		dataType: int64
		formatString: 0
		lineageTag: 34423855-306e-4920-a4aa-eafa802d233e
		summarizeBy: sum
		sourceColumn: Plan

		annotation SummarizationSetBy = Automatic

	column Actual
		dataType: int64
		formatString: 0
		lineageTag: a5d61f62-2b8d-421f-9940-da2c012d8ef2
		summarizeBy: sum
		sourceColumn: Actual

		annotation SummarizationSetBy = Automatic

	column Abnormal
		dataType: int64
		formatString: 0
		lineageTag: 0d426fb5-cc78-403f-9c13-cc8a7b9b775f
		summarizeBy: sum
		sourceColumn: Abnormal

		annotation SummarizationSetBy = Automatic

	column Good
		dataType: int64
		formatString: 0
		lineageTag: 0a183993-3773-450c-8765-8c19192a424f
		summarizeBy: sum
		sourceColumn: Good

		annotation SummarizationSetBy = Automatic

	column Date = DATEVALUE([Year ]&"-"&[Month]&"-"& 1)
		isHidden
		formatString: m/d/yyyy
		lineageTag: bb901b9d-cfbe-4496-bdf8-1a12804d08c1
		summarizeBy: none

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Action in Progress'
		dataType: int64
		formatString: 0
		lineageTag: 7cd96cb9-0b62-44f2-ab6a-987cd1ddcaeb
		summarizeBy: sum
		sourceColumn: Action in Progress

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Action Closed'
		dataType: int64
		formatString: 0
		lineageTag: 5397c816-7b26-4c1c-9705-ebe68f55050d
		summarizeBy: sum
		sourceColumn: Action Closed

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Year '
		dataType: string
		lineageTag: c4c42530-953d-48ca-b096-346597176306
		summarizeBy: none
		sourceColumn: "Year "

		annotation SummarizationSetBy = Automatic

	partition 'Night Inspection' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/CHJiaxingSecurity/Shared%20Documents/00%20Digital%20Huddle/Digital%20Huddle%20(Excel%E7%89%88-%E8%AF%95%E8%BF%90%E8%A1%8C%EF%BC%89/Supporting%20Document%20(Quality-Night%20Inspection)/Night%20Inspection%20Plan%20&%20Data%20(%20Update%20By%20Lina).xlsx"), null, true),
				    #"Dashboard Data_Sheet" = Source{[Item="Dashboard Data",Kind="Sheet"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(#"Dashboard Data_Sheet", each ([Column8] <> null)),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Removed Other Columns", each ([Column8] <> "Data Key In Table ( By Lina )")),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Filtered Rows1", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Plan", Int64.Type}, {"Actual", Int64.Type}, {"Abnormal", Int64.Type}, {"Good", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

