table 'On-duty Plan'
	lineageTag: e34a0df8-8a78-4041-92f7-70a19969563f

	column Area
		dataType: string
		lineageTag: 1e7cd43c-603f-4257-a847-91012f4bbdc8
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column Time
		dataType: string
		lineageTag: 04e847f6-b739-4808-85fd-4fc968055f21
		summarizeBy: none
		sourceColumn: Time
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Staff1
		dataType: string
		lineageTag: b7f5b917-fdb8-4feb-9c61-c76e33bedee1
		summarizeBy: none
		sourceColumn: Staff1

		annotation SummarizationSetBy = Automatic

	column Staff2
		dataType: string
		lineageTag: 8c06160e-ef30-461f-81b4-0abb1bf743a7
		summarizeBy: none
		sourceColumn: Staff2

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: string
		lineageTag: cfbc275f-a679-485a-a006-12699890a0e8
		summarizeBy: none
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	partition 'On-duty Plan' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/CHJiaxingSecurity/Shared%20Documents/00%20Digital%20Huddle/Security%20Huddle%20Update.xlsx"), null, true),
				    #"On-duty Today_Sheet" = Source{[Item="On-duty Today",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(#"On-duty Today_Sheet",1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Filled Down" = Table.FillDown(#"Promoted Headers",{"Column1"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Filled Down",{ "Column6", "Column7", "Column8", "Column9"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Column1", "Area"}, {"时间", "Time"}, {"人员1", "Staff1"}, {"人员2", "Staff2"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

