table Others
	lineageTag: cb2e5467-e090-4b46-adfe-71b5d5d447e1

	column 'No.'
		dataType: string
		lineageTag: 63ce3339-7c77-4920-8542-dc22b5eeca8a
		summarizeBy: none
		sourceColumn: No.

		annotation SummarizationSetBy = Automatic

	column WHO
		dataType: string
		lineageTag: c5dc42d3-3e60-4356-8247-4a0e323b0ff8
		summarizeBy: none
		sourceColumn: WHO

		annotation SummarizationSetBy = Automatic

	column What
		dataType: string
		lineageTag: 08f6a4f0-09e4-47ca-9503-f23314ef1273
		summarizeBy: none
		sourceColumn: What

		annotation SummarizationSetBy = Automatic

	partition Others = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/CHJiaxingSecurity/Shared%20Documents/00%20Digital%20Huddle/Security%20Huddle%20Update.xlsx"), null, true),
				    Others_Sheet = Source{[Item="Others",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(Others_Sheet,1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Removed Blank Rows" = Table.SelectRows(#"Promoted Headers", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Removed Blank Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

