table ParkingRate
	lineageTag: 35b60931-60f4-436b-92f8-e78a24d896ff

	column 日期
		dataType: string
		lineageTag: ee1f65f0-ee3f-4f69-94e3-d0cf5717de13
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

	column 南区
		dataType: double
		formatString: 0%;-0%;0%
		lineageTag: ce094839-de02-472a-87bd-140b765a624b
		summarizeBy: sum
		sourceColumn: 南区

		annotation SummarizationSetBy = Automatic

	column 北区
		dataType: double
		formatString: 0%;-0%;0%
		lineageTag: 9c8a0e87-8f7b-4a9e-9cdc-9869ef572087
		summarizeBy: sum
		sourceColumn: 北区

		annotation SummarizationSetBy = Automatic

	column 车辆溢出数南
		dataType: string
		lineageTag: edc55b24-0458-4146-a171-96082770b503
		summarizeBy: none
		sourceColumn: 车辆溢出数南

		annotation SummarizationSetBy = Automatic

	column 车辆溢出数北
		dataType: string
		lineageTag: cd0e8895-e5ad-4a93-aafb-5025bab406b4
		summarizeBy: none
		sourceColumn: 车辆溢出数北

		annotation SummarizationSetBy = Automatic

	partition ParkingRate = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/CHJiaxingSecurity/Shared%20Documents/00%20Digital%20Huddle/Security%20Huddle%20Update.xlsx"), null, true),
				    停车率_Sheet = Source{[Item="停车率",Kind="Sheet"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(停车率_Sheet,{"Column28", "Column29"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each ([Column28] <> null) and ([Column29] <> null)),
				    #"Transposed Table" = Table.Transpose(#"Filtered Rows"),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Transposed Table", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"南区", Percentage.Type}, {"北区", Percentage.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

