table 'Penetration Test'
	lineageTag: 56b491a8-142d-4b8f-a817-b89e0c3a04b5

	column Title
		dataType: string
		lineageTag: 4b8fd5db-8ebf-4814-a838-145b655e446b
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: c86efa02-7e81-4e0c-a0cf-668c5b133ccd
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 30072525-bcff-4eb0-8a77-8b5b2140422d
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column 'Penetration Area'
		dataType: string
		isHidden
		lineageTag: 33c2b7f8-6f30-4892-8791-01b608088a99
		summarizeBy: none
		sourceColumn: Penetration Area
		sortByColumn: SortOrder

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Penetration_Result
		dataType: string
		lineageTag: 7f91a1ab-ec87-44df-969f-d12e2d48d4cd
		summarizeBy: none
		sourceColumn: Penetration_Result

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 99fe0d9a-1d38-4cbe-9254-b7acc8cf3e0b
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Weekname
		dataType: string
		lineageTag: e8ee88c0-c8aa-40ef-a282-5da329527487
		summarizeBy: none
		sourceColumn: Weekname

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: string
		lineageTag: 56c2df19-a03c-4446-92c2-4297581afe1b
		summarizeBy: none
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = Automatic

	column Status =
			
			IF(
			    'Penetration Test'[Penetration_Result]="Success",
			    "✅",
			    "❌"
			)
		lineageTag: a721fb66-e5bc-4e86-903b-596b12556b9f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column SortOrder
		dataType: double
		lineageTag: be50feef-9792-4495-9ea1-bf8d86f082ca
		summarizeBy: sum
		sourceColumn: SortOrder

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Penetration Test' = m
		mode: import
		source =
				let
				    Source = Security_D,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Category] = "Penetration Test")),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Title", "Category", "Description", "Date", "Penetration Area", "Penetration_Result", "Weekname", "DayOfMonth"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Removed Other Columns", "SortOrder", each if [Penetration Area] = "ESPA" then 1 else if [Penetration Area] = "Non-ESPA" then 2 else if [Penetration Area] = "LCC" then 3 else null, type number)
				in
				    #"Added Conditional Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

