table 'SCL Availability'
	lineageTag: 23eb92a8-ddb8-46b3-b00a-1699e648d6e3

	column Area
		dataType: string
		lineageTag: 713bde9c-8c37-4be3-96c0-b1333bf1134b
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column Availability
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ce25ea38-8ced-41ce-8f44-abe67eef12ed
		summarizeBy: sum
		sourceColumn: Availability

		annotation SummarizationSetBy = Automatic

	partition 'SCL Availability' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/CHJiaxingSecurity/Shared%20Documents/00%20Digital%20Huddle/Security%20Huddle%20Update.xlsx"), null, true),
				    #"SCL Availability_Sheet" = Source{[Item="SCL Availability",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"SCL Availability_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Availability", Percentage.Type}, {"Area", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

