table Product
	lineageTag: 0a76033f-f6eb-4f96-85d5-b2ed0cabf573

	column ProductKey
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: 8ab76717-6f64-4d82-8d01-6da3b62d981c
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Product Code'
		dataType: string
		isHidden
		lineageTag: 1154a93a-6486-4fc3-a1c0-6aa131a9153a
		summarizeBy: none
		sourceColumn: Product Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: db936b74-aa29-496f-a90e-5d6fdda4f561
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: string
		lineageTag: 2e17b22f-2476-4399-a859-c8215c492fa7
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 9f6b2494-3493-4a50-8169-dc17ac5eafc2
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: b50d4eb1-cf9f-4af6-a378-b2da4bf85cf6
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column Weight
		dataType: double
		isHidden
		formatString: #,0.00
		lineageTag: b72ced91-e72e-49ed-8d31-ea4399561d5b
		summarizeBy: none
		sourceColumn: Weight

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Unit Cost'
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: 1e9a7ad0-3a26-4676-9a3d-a5961c82908e
		summarizeBy: none
		sourceColumn: Unit Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Unit Price'
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: 8c8d80bf-4810-40ef-81ad-251ba1e2dcff
		summarizeBy: none
		sourceColumn: Unit Price

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Available Date'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 9b6f193f-a618-4d6b-8da7-ec5b3c74d14a
		summarizeBy: none
		sourceColumn: Available Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: ffd02193-e624-4b5f-ab92-784868a95280
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: abd418ee-b87c-4896-9713-6c3c8ba8f482
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	hierarchy Products
		lineageTag: af1f10c1-f408-48e8-a106-c5aa360ee140

		level Category
			lineageTag: 08c8a490-dd3b-41dc-a6c4-c481aaa2c397
			column: Category

		level Subcategory
			lineageTag: 054e2fd8-4a8d-4086-8a89-e86a016a9424
			column: Subcategory

		level 'Product Name'
			lineageTag: da1573cd-79af-4cac-84d9-147673175f3d
			column: 'Product Name'

	partition 'DaxBook Product' = m
		mode: import
		source =
				let
				    Source = Sql.Database("Demo", "ContosoRetailDW"),
				    DaxBook_Product = Source{[Schema="DaxBook",Item="Product"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(DaxBook_Product,{"Class", "Style", "Size", "Stock Type Code", "Stock Type", "Status", "Product Description"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns",{"ProductSubcategoryKey"},#"Product Subcategory",{"ProductSubcategoryKey"},"Product Subcategory",JoinKind.LeftOuter),
				    #"Expanded Product Subcategory" = Table.ExpandTableColumn(#"Merged Queries", "Product Subcategory", {"Subcategory", "ProductCategoryKey"}, {"Subcategory", "ProductCategoryKey"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Expanded Product Subcategory",{"ProductSubcategoryKey"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Removed Columns1",{"ProductCategoryKey"},#"Product Category",{"ProductCategoryKey"},"Product Category",JoinKind.LeftOuter),
				    #"Expanded Product Category" = Table.ExpandTableColumn(#"Merged Queries1", "Product Category", {"Category"}, {"Category"}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Expanded Product Category",{"ProductCategoryKey", "Weight Unit Measure"})
				in
				    #"Removed Columns2"

		annotation IsQueryEditorUsed = False

		annotation QueryEditorSerialization

		annotation TableWidgetSerialization

	annotation _TM_ExtProp_QueryDefinition = SELECT * FROM [Product]

	annotation _TM_ExtProp_DbTableName = 525

	annotation IsQueryEditorUsed = False

	annotation QueryEditorSerialization

	annotation TableWidgetSerialization

	annotation DataMarketWebBaseUrl

	annotation DataMarketWebQueryUrl

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

