table '400V 电表'
	lineageTag: 2ed8f59e-2a95-4f46-912b-e5d76976c6a7

	measure Total_Avgofpowerusageperline = SUM('400V 电表'[Value])/[linequantity]
		lineageTag: e14a300d-d538-4404-b9e6-37f2641644a0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'per hour power usage' = ```
			
			var Total_Avgofpowerusageper = SUM('400V 电表'[Value])
			VAR Totalmouldinghours=SUM('Moulding Hour Summary'[Moulding Hours])
			VAR perhourusage=DIVIDE(Total_Avgofpowerusageper,Totalmouldinghours)
			RETURN perhourusage
			
			```
		lineageTag: 9285bfe1-4395-4ee4-b642-247fde46d75c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cabinet
		dataType: string
		isHidden
		lineageTag: 4658b76c-5014-40f4-8d37-3c6697d189a9
		summarizeBy: none
		sourceColumn: Cabinet

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SN
		dataType: string
		lineageTag: fb1e9810-fcfe-4ac9-a69e-ebce57c77ff2
		summarizeBy: none
		sourceColumn: SN

		annotation SummarizationSetBy = Automatic

	column 'End user'
		dataType: string
		lineageTag: 871f2286-abca-40b3-a0de-8562fdafb954
		summarizeBy: none
		sourceColumn: End user

		annotation SummarizationSetBy = Automatic

	column 使用区域
		dataType: string
		lineageTag: 879b6315-0ccc-4bb2-bc58-92b8072b0a2d
		summarizeBy: none
		sourceColumn: 使用区域

		annotation SummarizationSetBy = Automatic

	column 功能分类
		dataType: string
		lineageTag: 1ac943e6-5f4b-48c5-bd06-fd50125144d6
		summarizeBy: none
		sourceColumn: 功能分类

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: fa7d67fd-ce5b-4b34-82cc-79b55d7b80b0
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Value
		dataType: double
		lineageTag: 6ac079ec-0927-47f1-9743-f551dded16ca
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column key = [SN]&"_"&[Date]
		lineageTag: 16ceb324-7079-4e35-a44d-11266df9e394
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition '400V 电表' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/JIALFACTECH/Shared%20Documents/18%20%E8%83%BD%E6%BA%90%E4%BF%A1%E6%81%AF%E7%AE%A1%E7%90%86/01%20Energy%20Data%20%E8%83%BD%E6%BA%90%E6%95%B0%E6%8D%AE/%E8%83%BD%E6%BA%90%E4%B8%AD%E5%BF%83%E6%95%B0%E6%8D%AE%E8%AE%B0%E5%BD%95%E8%A1%A8%202025.xlsx"), null, true),
				    #"400V 电表_Sheet" = Source{[Item="400V 电表",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"400V 电表_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"所有电表(400V)", type text}, {"Column2", type any}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type any}, {"Column27", type any}, {"Column28", type any}, {"Column29", type any}, {"Column30", type any}, {"Column31", type any}, {"Column32", type any}, {"Column33", type any}, {"Column34", type any}, {"Column35", type any}, {"Column36", type any}, {"Column37", type any}, {"Column38", type any}, {"Column39", type any}, {"Column40", type any}, {"Column41", type any}, {"Column42", type any}, {"Column43", type any}, {"Column44", type any}, {"Column45", type any}, {"Column46", type any}, {"Column47", type any}, {"Column48", type any}, {"Column49", type any}, {"Column50", type any}, {"Column51", type any}, {"Column52", type any}, {"Column53", type any}, {"Column54", type any}, {"Column55", type any}, {"Column56", type any}, {"Column57", type any}, {"Column58", type any}, {"Column59", type any}, {"Column60", type any}, {"Column61", type any}, {"Column62", type any}, {"Column63", type any}, {"Column64", type any}, {"Column65", type any}, {"Column66", type any}, {"Column67", type any}, {"Column68", type any}, {"Column69", type any}, {"Column70", type any}, {"Column71", type any}, {"Column72", type any}, {"Column73", type any}, {"Column74", type any}, {"Column75", type any}, {"Column76", type any}, {"Column77", type any}, {"Column78", type any}, {"Column79", type any}, {"Column80", type any}, {"Column81", type any}, {"Column82", type any}, {"Column83", type any}, {"Column84", type any}, {"Column85", type any}, {"Column86", type any}, {"Column87", type any}, {"Column88", type any}, {"Column89", type any}, {"Column90", type any}, {"Column91", type any}, {"Column92", type any}, {"Column93", type any}, {"Column94", type any}, {"Column95", type any}, {"Column96", type any}, {"Column97", type any}, {"Column98", type any}, {"Column99", type any}, {"Column100", type any}, {"Column101", type any}, {"Column102", type any}, {"Column103", type any}, {"Column104", type any}, {"Column105", type any}, {"Column106", type any}, {"Column107", type any}, {"Column108", type any}, {"Column109", type any}, {"Column110", type any}, {"Column111", type any}, {"Column112", type any}, {"Column113", type any}, {"Column114", type any}, {"Column115", type any}, {"Column116", type any}, {"Column117", type any}, {"Column118", type any}, {"Column119", type any}, {"Column120", type any}, {"Column121", type any}, {"Column122", type any}, {"Column123", type any}, {"Column124", type any}, {"Column125", type any}, {"Column126", type any}, {"Column127", type any}, {"Column128", type any}, {"Column129", type any}, {"Column130", type any}, {"Column131", type any}, {"Column132", type any}, {"Column133", type any}, {"Column134", type any}, {"Column135", type any}, {"Column136", type any}, {"Column137", type any}, {"Column138", type any}, {"Column139", type any}, {"Column140", type any}, {"Column141", type any}, {"Column142", type any}, {"Column143", type any}, {"Column144", type any}, {"Column145", type any}, {"Column146", type any}, {"Column147", type any}, {"Column148", type any}, {"Column149", type any}, {"Column150", type any}, {"Column151", type any}, {"Column152", type any}, {"Column153", type any}, {"Column154", type any}, {"Column155", type any}, {"Column156", type any}, {"Column157", type any}, {"Column158", type any}, {"Column159", type any}, {"Column160", type any}, {"Column161", type any}, {"Column162", type any}, {"Column163", type any}, {"Column164", type any}, {"Column165", type any}, {"Column166", type any}, {"Column167", type any}, {"Column168", type any}, {"Column169", type any}, {"Column170", type any}, {"Column171", type any}, {"Column172", type any}, {"Column173", type any}, {"Column174", type any}, {"Column175", type any}, {"Column176", type any}, {"Column177", type any}, {"Column178", type any}, {"Column179", type any}, {"Column180", type any}, {"Column181", type date}, {"Column182", type date}, {"Column183", type date}, {"Column184", type date}, {"Column185", type date}, {"Column186", type date}, {"Column187", type date}, {"Column188", type date}, {"Column189", type date}, {"Column190", type date}, {"Column191", type date}, {"Column192", type date}, {"Column193", type any}, {"Column194", type date}, {"Column195", type date}, {"Column196", type date}, {"Column197", type date}, {"Column198", type date}, {"Column199", type date}, {"Column200", type date}, {"Column201", type date}, {"Column202", type date}, {"Column203", type date}, {"Column204", type date}, {"Column205", type date}, {"Column206", type date}, {"Column207", type date}, {"Column208", type date}, {"Column209", type date}, {"Column210", type date}, {"Column211", type date}, {"Column212", type date}, {"Column213", type date}, {"Column214", type date}, {"Column215", type date}, {"Column216", type date}, {"Column217", type date}, {"Column218", type date}, {"Column219", type date}, {"Column220", type date}, {"Column221", type date}, {"Column222", type date}, {"Column223", type date}, {"Column224", type date}, {"Column225", type any}, {"Column226", type date}, {"Column227", type date}, {"Column228", type date}, {"Column229", type date}, {"Column230", type date}, {"Column231", type date}, {"Column232", type date}, {"Column233", type date}, {"Column234", type date}, {"Column235", type date}, {"Column236", type date}, {"Column237", type date}, {"Column238", type date}, {"Column239", type date}, {"Column240", type date}, {"Column241", type date}, {"Column242", type date}, {"Column243", type date}, {"Column244", type date}, {"Column245", type date}, {"Column246", type date}, {"Column247", type date}, {"Column248", type date}, {"Column249", type date}, {"Column250", type date}, {"Column251", type date}, {"Column252", type date}, {"Column253", type date}, {"Column254", type date}, {"Column255", type date}, {"Column256", type date}, {"Column257", type any}, {"Column258", type date}, {"Column259", type date}, {"Column260", type date}, {"Column261", type date}, {"Column262", type date}, {"Column263", type date}, {"Column264", type date}, {"Column265", type date}, {"Column266", type date}, {"Column267", type date}, {"Column268", type date}, {"Column269", type date}, {"Column270", type date}, {"Column271", type date}, {"Column272", type date}, {"Column273", type date}, {"Column274", type date}, {"Column275", type date}, {"Column276", type date}, {"Column277", type date}, {"Column278", type date}, {"Column279", type date}, {"Column280", type date}, {"Column281", type date}, {"Column282", type date}, {"Column283", type date}, {"Column284", type date}, {"Column285", type date}, {"Column286", type date}, {"Column287", type date}, {"Column288", type any}, {"Column289", type date}, {"Column290", type date}, {"Column291", type date}, {"Column292", type date}, {"Column293", type date}, {"Column294", type date}, {"Column295", type date}, {"Column296", type date}, {"Column297", type date}, {"Column298", type date}, {"Column299", type date}, {"Column300", type date}, {"Column301", type date}, {"Column302", type date}, {"Column303", type date}, {"Column304", type date}, {"Column305", type date}, {"Column306", type date}, {"Column307", type date}, {"Column308", type date}, {"Column309", type date}, {"Column310", type date}, {"Column311", type date}, {"Column312", type date}, {"Column313", type date}, {"Column314", type date}, {"Column315", type date}, {"Column316", type date}, {"Column317", type date}, {"Column318", type date}, {"Column319", type date}, {"Column320", type any}, {"Column321", type date}, {"Column322", type date}, {"Column323", type date}, {"Column324", type date}, {"Column325", type date}, {"Column326", type date}, {"Column327", type date}, {"Column328", type date}, {"Column329", type date}, {"Column330", type date}, {"Column331", type date}, {"Column332", type date}, {"Column333", type date}, {"Column334", type date}, {"Column335", type date}, {"Column336", type date}, {"Column337", type date}, {"Column338", type date}, {"Column339", type date}, {"Column340", type date}, {"Column341", type date}, {"Column342", type date}, {"Column343", type date}, {"Column344", type date}, {"Column345", type date}, {"Column346", type date}, {"Column347", type date}, {"Column348", type date}, {"Column349", type date}, {"Column350", type date}, {"Column351", type any}, {"Column352", type date}, {"Column353", type date}, {"Column354", type date}, {"Column355", type date}, {"Column356", type date}, {"Column357", type date}, {"Column358", type date}, {"Column359", type date}, {"Column360", type date}, {"Column361", type date}, {"Column362", type date}, {"Column363", type date}, {"Column364", type date}, {"Column365", type date}, {"Column366", type date}, {"Column367", type date}, {"Column368", type date}, {"Column369", type date}, {"Column370", type date}, {"Column371", type date}, {"Column372", type date}, {"Column373", type date}, {"Column374", type date}, {"Column375", type date}, {"Column376", type date}, {"Column377", type date}, {"Column378", type date}, {"Column379", type date}, {"Column380", type date}, {"Column381", type date}, {"Column382", type date}, {"Column383", type any}}),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Filled Down" = Table.FillDown(#"Promoted Headers1",{"Cabinet"}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Filled Down", {"Cabinet", "SN", "End user", "使用区域", "功能分类"}, "Attribute", "Value"),
				    #"Filtered Rows" = Table.SelectRows(#"Unpivoted Columns", each ([Attribute] <> "7-6月" and [Attribute] <> "Annual" and [Attribute] <> "APR" and [Attribute] <> "AUG" and [Attribute] <> "DEC" and [Attribute] <> "FEB" and [Attribute] <> "JAN" and [Attribute] <> "JUL" and [Attribute] <> "JUN" and [Attribute] <> "MAR" and [Attribute] <> "MAY" and [Attribute] <> "NOV" and [Attribute] <> "OCT" and [Attribute] <> "SEP")),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Filtered Rows",{{"Attribute", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type2",{{"Attribute", "Date"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns",{{"Value", type number}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type3", {{"Value", 0}})
				in
				    #"Replaced Errors"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

