table 'Produced Weight Summary'
	lineageTag: 4729198a-8bde-4801-9fd6-189540bbed4f

	measure pertonppower =
			
			var Total_powerusageper = SUM('400V 电表'[Value])
			VAR Totalproducedweight=SUM('Produced Weight Summary'[Produced Weight (Tons)])
			VAR pertonppower=DIVIDE(Total_powerusageper,Totalproducedweight)
			RETURN pertonppower
		lineageTag: 1deffbae-8101-43d1-a140-04734fc03b19

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Calendar day'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 509b5d06-3b14-485b-885a-370794306d78
		summarizeBy: none
		sourceColumn: Calendar day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Line
		dataType: int64
		formatString: 0
		lineageTag: f1ebc820-a641-43e4-ad43-6481d87066a3
		summarizeBy: sum
		sourceColumn: Line

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Produced Weight (Tons)'
		dataType: double
		lineageTag: 741a690f-9af3-4e67-9d8c-b685d8454a04
		summarizeBy: sum
		sourceColumn: Produced Weight (Tons)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column key1 = [Line]&"_"&[Calendar day]
		lineageTag: 6978cb91-d599-4a75-9aa2-9c76f6c45c38
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Produced Weight Summary' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup-my.sharepoint.com/personal/guochun_li_lego_com/Documents/Moulding%20Hours%20%20Produced%20Weight%20(2025.01-2025.05)%2020250604%20(1).xlsx"), null, true),
				    #"Produced Weight Summary_Sheet" = Source{[Item="Produced Weight Summary",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Produced Weight Summary_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Calendar day", type date}, {"Line", Int64.Type}, {"Produced Weight (Tons)", type number}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

