table Summary
	isHidden
	lineageTag: d06468e0-7b44-42ed-a268-dbdb269c3d48

	measure linequantity = ```
			
			IF(SUM('400V 电表'[Value])>0,
			    IF(HASONEVALUE(Summary[Line]),CALCULATE(DISTINCTCOUNT('Summary'[Line]),REMOVEFILTERS('Summary'[Line])),1))
			
			```
		formatString: 0
		isHidden
		lineageTag: 7afea584-7e17-4982-b553-f750d1255c4e

		changedProperty = IsHidden

	column Line
		dataType: string
		isHidden
		lineageTag: f5349e8e-c03c-49ca-b4fa-227bbca33f56
		summarizeBy: none
		sourceColumn: Line

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Calendar day'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: d9598ae8-2dd1-4872-b5f5-43a59f1ace8c
		summarizeBy: none
		sourceColumn: Calendar day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Moulding Hours'
		dataType: double
		isHidden
		lineageTag: ccaa18e9-a445-436e-b416-069939f3b01e
		summarizeBy: sum
		sourceColumn: Moulding Hours

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Produced Weight (Tons)'
		dataType: double
		isHidden
		lineageTag: f50670ab-cc80-4545-9658-2d69ca6f617d
		summarizeBy: sum
		sourceColumn: Produced Weight (Tons)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SN
		dataType: string
		lineageTag: b01c6418-758d-4224-9cc0-36f29b037c3c
		summarizeBy: none
		sourceColumn: SN

		annotation SummarizationSetBy = Automatic

	partition Summary = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup-my.sharepoint.com/personal/guochun_li_lego_com/Documents/Desktop/Moulding%20Hours%20%20Produced%20Weight%20(2025.01-2025.05)%2020250604.xlsx"), null, true),
				    Summary_Sheet = Source{[Item="Summary",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Summary_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Column1", type text}, {"Column2", type text}, {"Total Kwh", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"Total Working Hour", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Kwh/Hour（Average Machine）", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Weight(Tons)", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Moulding components Tons/Kwh（Average Machines）", type any}, {"Column25", type any}, {"Column26", type any}, {"Column27", type any}, {"Column28", type any}, {"Moulding components#(lf)KG/Kwh（Average Machines）", type any}}),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers1",{{"SN", type text}, {"Line", type text}, {"JAN", Int64.Type}, {"FEB", Int64.Type}, {"MAR", Int64.Type}, {"APR", Int64.Type}, {"MAY", Int64.Type}, {"JAN_1", type number}, {"FEB_2", type number}, {"MAR_3", type number}, {"APR_4", type number}, {"MAY_5", type number}, {"JAN_6", type any}, {"FEB_7", type any}, {"MAR_8", type any}, {"APR_9", type any}, {"MAY_10", type any}, {"Average", type any}, {"JAN_11", type number}, {"FEB_12", type number}, {"MAR_13", type number}, {"APR_14", type number}, {"MAY_15", type number}, {"JAN_16", type number}, {"FEB_17", type number}, {"MAR_18", type number}, {"APR_19", type number}, {"MAY_20", type number}, {"Average_21", type number}}),
				    #"Extracted Text After Delimiter" = Table.TransformColumns(#"Changed Type1", {{"Line", each Text.AfterDelimiter(_, "line "), type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Extracted Text After Delimiter",{"JAN", "FEB", "MAR", "APR", "MAY", "JAN_1", "FEB_2", "MAR_3", "APR_4", "MAY_5", "JAN_6", "FEB_7", "MAR_8", "APR_9", "MAY_10", "Average", "JAN_11", "FEB_12", "MAR_13", "APR_14", "MAY_15", "JAN_16", "FEB_17", "MAR_18", "APR_19", "MAY_20", "Average_21"}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Columns", "Line", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"Line.1", "Line.2", "Line.3", "Line.4"}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Split Column by Delimiter", {"SN"}, "Attribute", "Value"),
				    #"Removed Columns1" = Table.RemoveColumns(#"Unpivoted Columns",{"Attribute"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"Value", "Line"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns",{{"Line", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type2", {"Line"}, #"Moulding Hour Summary", {"Line"}, "Moulding Hour Summary", JoinKind.LeftOuter),
				    #"Expanded Moulding Hour Summary" = Table.ExpandTableColumn(#"Merged Queries", "Moulding Hour Summary", {"Calendar day", "Moulding Hours"}, {"Calendar day", "Moulding Hours"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded Moulding Hour Summary", {"Line", "Calendar day"}, #"Produced Weight Summary", {"Line", "Calendar day"}, "Produced Weight Summary", JoinKind.LeftOuter),
				    #"Expanded Produced Weight Summary" = Table.ExpandTableColumn(#"Merged Queries1", "Produced Weight Summary", {"Produced Weight (Tons)"}, {"Produced Weight (Tons)"})
				in
				    #"Expanded Produced Weight Summary"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

